ALTER ROLE [db_owner] ADD MEMBER [BA-818]
GO
ALTER ROLE [db_owner] ADD MEMBER [D2KT\Deepali.Phirake]
GO
ALTER ROLE [db_owner] ADD MEMBER [demoenpa]
GO
ALTER ROLE [db_owner] ADD MEMBER [DevTeam]
GO
ALTER ROLE [db_owner] ADD MEMBER [DF647]
GO
ALTER ROLE [db_owner] ADD MEMBER [DF650]
GO
ALTER ROLE [db_owner] ADD MEMBER [DF732]
GO
ALTER ROLE [db_owner] ADD MEMBER [DF836]
GO
ALTER ROLE [db_owner] ADD MEMBER [DF921]
GO
ALTER ROLE [db_owner] ADD MEMBER [DM085]
GO
ALTER ROLE [db_owner] ADD MEMBER [DM1045]
GO
ALTER ROLE [db_owner] ADD MEMBER [DM1070]
GO
ALTER ROLE [db_owner] ADD MEMBER [DM672]
GO
ALTER ROLE [db_owner] ADD MEMBER [DM676]
GO
ALTER ROLE [db_owner] ADD MEMBER [DM748]
GO
ALTER ROLE [db_owner] ADD MEMBER [DM778]
GO
ALTER ROLE [db_owner] ADD MEMBER [dm805]
GO
ALTER ROLE [db_owner] ADD MEMBER [DM838]
GO
ALTER ROLE [db_owner] ADD MEMBER [DM-844]
GO
ALTER ROLE [db_owner] ADD MEMBER [DM907]
GO
ALTER ROLE [db_owner] ADD MEMBER [DM939]
GO
ALTER ROLE [db_owner] ADD MEMBER [DM957]
GO
ALTER ROLE [db_owner] ADD MEMBER [DM973]
GO
ALTER ROLE [db_owner] ADD MEMBER [kmth]
GO
ALTER ROLE [db_owner] ADD MEMBER [ReportTeam]
GO
ALTER ROLE [db_owner] ADD MEMBER [RF1100]
GO
ALTER ROLE [db_owner] ADD MEMBER [RM1025]
GO
ALTER ROLE [db_owner] ADD MEMBER [RM1086]
GO
ALTER ROLE [db_owner] ADD MEMBER [RM964]
GO
ALTER ROLE [db_owner] ADD MEMBER [TestingTeam]
GO
ALTER ROLE [db_owner] ADD MEMBER [TF755]
GO
ALTER ROLE [db_owner] ADD MEMBER [TF807]
GO
ALTER ROLE [db_owner] ADD MEMBER [TM1063]
GO
ALTER ROLE [db_owner] ADD MEMBER [TM1067]
GO
ALTER ROLE [db_owner] ADD MEMBER [TM429]
GO
ALTER ROLE [db_owner] ADD MEMBER [TM744]
GO
ALTER ROLE [db_owner] ADD MEMBER [TM797]
GO
ALTER ROLE [db_owner] ADD MEMBER [TM859]
GO
ALTER ROLE [db_owner] ADD MEMBER [TM-859]
GO
