CREATE TABLE [CurDat].[DerivativeDetail]
(
[EntityKey] [bigint] NOT NULL IDENTITY(1, 1),
[DerivativeEntityID] [int] NOT NULL,
[CustomerACID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DerivativeRefNo] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Duedate] [date] NULL,
[DueAmt] [decimal] (16, 2) NULL,
[OsAmt] [decimal] (16, 2) NULL,
[POS] [decimal] (16, 2) NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NOT NULL,
[EffectiveToTimeKey] [int] NOT NULL,
[CreatedBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[DateofData] [date] NULL,
[SourceSystem] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UCIC_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FLGDEG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEGREASON] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DPD] [int] NULL,
[FLGUPG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpgDate] [date] NULL,
[DBTDate] [date] NULL,
[PROVISIONALT_KEY] [int] NULL,
[InitialAssetAlt_Key] [int] NULL,
[InitialNPIDt] [date] NULL,
[DPD_DivOverdue] [int] NULL,
[FinalAssetClassAlt_Key] [int] NULL,
[NPIDt] [date] NULL,
[AssetClass_AltKey] [smallint] NULL,
[TotalProvison] [decimal] (18, 2) NULL,
[InstrumentName] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverDueSinceDt] [date] NULL,
[DueAmtReceivable] [decimal] (18, 2) NULL,
[MTMIncomeAmt] [decimal] (18, 2) NULL,
[CouponDate] [date] NULL,
[CouponAmt] [decimal] (18, 2) NULL,
[CouponOverDueSinceDt] [date] NULL,
[OverdueCouponAmt] [decimal] (18, 2) NULL,
[DPD_CouponOverDue] [int] NULL,
[ChangeFields] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlgSMA] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMA_Dt] [date] NULL,
[SMA_Class] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMA_Reason] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddlProvision] [decimal] (18, 2) NULL,
[AddlProvisionPer] [decimal] (5, 2) NULL,
[FlgMoc] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MocBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOC_Date] [date] NULL,
[MOC_Reason] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Asset_Norm] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [CurDat].[DerivativeDetail] ADD CONSTRAINT [DerivativeDetail_DerivativeEntityID] PRIMARY KEY NONCLUSTERED ([DerivativeEntityID], [EffectiveFromTimeKey], [EffectiveToTimeKey]) ON [PRIMARY]
GO
