CREATE TABLE [CurDat].[ADVFACDLDETAIL]
(
[ENTITYKEY] [bigint] NOT NULL,
[AccountEntityId] [int] NOT NULL,
[Principal] [decimal] (14, 0) NULL,
[RepayModeAlt_Key] [smallint] NULL,
[NoOfInstall] [smallint] NULL,
[InstallAmt] [decimal] (14, 0) NULL,
[FstInstallDt] [date] NULL,
[LastInstallDt] [date] NULL,
[Tenure_Months] [smallint] NULL,
[MarginAmt] [decimal] (14, 0) NULL,
[CommodityAlt_Key] [smallint] NULL,
[RephaseAlt_Key] [smallint] NULL,
[RephaseDt] [date] NULL,
[IntServiced] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SuspendedInterest] [decimal] (14, 0) NULL,
[DerecognisedInterest1] [decimal] (14, 0) NULL,
[DerecognisedInterest2] [decimal] (14, 0) NULL,
[AdjReasonAlt_Key] [smallint] NULL,
[LcNo] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LcAmt] [decimal] (14, 0) NULL,
[LcIssuingBankAlt_Key] [smallint] NULL,
[ResetFrequency] [smallint] NULL,
[ResetDt] [date] NULL,
[Moratorium] [smallint] NULL,
[FirstInstallDtInt] [date] NULL,
[ContExcsSinceDt] [date] NULL,
[loanPeriod] [int] NULL,
[ClaimType] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimCoverAmt] [decimal] (14, 0) NULL,
[ClaimLodgedDt] [date] NULL,
[ClaimLodgedAmt] [decimal] (14, 0) NULL,
[ClaimRecvDt] [date] NULL,
[ClaimReceivedAmt] [decimal] (14, 0) NULL,
[ClaimRate] [int] NULL,
[RefSystemAcid] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NOT NULL,
[EffectiveToTimeKey] [int] NOT NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [datetime] NULL,
[InstRepaymentDt] [date] NULL,
[ScrCrError] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InttRepaymentDt] [date] NULL,
[ScheDuleNo] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MocStatus] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MocDate] [smalldatetime] NULL,
[MocTypeAlt_Key] [int] NULL,
[UnAppliedIntt] [decimal] (14, 0) NULL,
[NxtInstDay] [smallint] NULL,
[PrplOvduAftrMth] [smallint] NULL,
[PrplOvduAftrDay] [smallint] NULL,
[InttOvduAftrDay] [smallint] NULL,
[InttOvduAftrMth] [smallint] NULL,
[PrinOvduEndMth] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InttOvduEndMth] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ScrCrErrorSeq] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoverExpiryDt] [date] NULL
) ON [PRIMARY]
GO
ALTER TABLE [CurDat].[ADVFACDLDETAIL] ADD CONSTRAINT [CK__ADVFACDLD__Effec__47D18CA4] CHECK (([EffectiveToTimeKey]=(49999)))
GO
ALTER TABLE [CurDat].[ADVFACDLDETAIL] ADD CONSTRAINT [CK__ADVFACDLD__Effec__48C5B0DD] CHECK (([EffectiveToTimeKey]=(49999)))
GO
ALTER TABLE [CurDat].[ADVFACDLDETAIL] ADD CONSTRAINT [ADVFACDLDETAIL_AccountEntityID] PRIMARY KEY NONCLUSTERED ([AccountEntityId], [EffectiveFromTimeKey], [EffectiveToTimeKey]) ON [PRIMARY]
GO
