CREATE TABLE [CurDat].[AdvFacNFDetail]
(
[EntityKey] [bigint] NOT NULL IDENTITY(1, 1),
[AccountEntityId] [int] NOT NULL,
[D2KFacilityID] [int] NULL,
[GLAlt_key] [smallint] NULL,
[Operative_Acid] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LCBG_TYPE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LCBGNo] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LcBgAmt] [decimal] (16, 2) NULL,
[OriginDt] [date] NULL,
[EffectiveDt] [date] NULL,
[ExpiryDt] [date] NULL,
[ExtensionDt] [date] NULL,
[TypeAlt_Key] [smallint] NULL,
[NatureAlt_Key] [smallint] NULL,
[BeneficiaryType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BeneficiaryName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Balance] [decimal] (16, 2) NULL,
[BalanceInCurrency] [decimal] (16, 4) NULL,
[CurrencyAlt_Key] [smallint] NULL,
[CountryAlt_Key] [smallint] NULL,
[NegotiatingBank] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MarginType] [smallint] NULL,
[MarginAmt] [decimal] (14, 0) NULL,
[PurposeAlt_Key] [smallint] NULL,
[ShipmentDt] [date] NULL,
[CoveredByBank] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoveredByBankAlt_Key] [smallint] NULL,
[InvocationDt] [date] NULL,
[Commission] [decimal] (16, 2) NULL,
[BillReceived] [decimal] (18, 0) NULL,
[BillsUnderCollAmt] [decimal] (20, 4) NULL,
[FundedConversionDt] [date] NULL,
[Datepaid] [date] NULL,
[RecoveryDt] [date] NULL,
[CounterGuar] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CorresBankCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CorresBrCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimDt] [date] NULL,
[NFFacilityNo] [smallint] NULL,
[Periodicity] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CommissionDue] [decimal] (16, 2) NULL,
[DueDateOfRecovery] [date] NULL,
[CommOnDuedateYN] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DelayReason] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PresentPosition] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmmountRecovered] [decimal] (16, 2) NULL,
[ScrCrError] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdjDt] [date] NULL,
[AdjReasonAlt_Key] [smallint] NULL,
[EntityClosureDate] [date] NULL,
[EntityClosureReasonAlt_Key] [smallint] NULL,
[RefCustomerId] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefSystemAcId] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NOT NULL,
[EffectiveToTimeKey] [int] NOT NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[MocStatus] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MocDate] [smalldatetime] NULL,
[MocTypeAlt_Key] [int] NULL,
[GovtGurantee] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GovGurAmt] [decimal] (14, 0) NULL,
[ScrCrErrorSeq] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ApplicationDt] [date] NULL,
[ClaimExpiryDt] [date] NULL,
[InvocationStatusAlt_Key] [smallint] NULL,
[provision] [decimal] (16, 2) NULL,
[MarginAccNo] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [CurDat].[AdvFacNFDetail] ADD CONSTRAINT [AdvFacNFDetail_PK] PRIMARY KEY NONCLUSTERED ([EffectiveFromTimeKey], [EffectiveToTimeKey], [AccountEntityId], [LCBGNo]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
