CREATE TABLE [CurDat].[ADVCUSTFINANCIALDETAIL]
(
[ENTITYKEY] [bigint] NOT NULL IDENTITY(1, 1),
[CustomerEntityId] [int] NOT NULL,
[BranchCode] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TotLimitFunded] [decimal] (14, 0) NULL,
[TotLimitNF] [decimal] (14, 0) NULL,
[TotOsFunded] [decimal] (16, 2) NULL,
[TotOsNF] [decimal] (16, 2) NULL,
[TotOverDue] [decimal] (14, 0) NULL,
[TotCadu] [decimal] (14, 0) NULL,
[TotCad] [decimal] (14, 0) NULL,
[Cust_AssetClassAlt_Key] [smallint] NULL,
[TotProvision] [decimal] (14, 0) NULL,
[TotAdditionalProvision] [decimal] (14, 0) NULL,
[TotGenericAddlProvision] [decimal] (14, 0) NULL,
[TotUnappliedInt] [decimal] (14, 0) NULL,
[EntityClosureDate] [date] NULL,
[EntityClosureReasonAlt_Key] [smallint] NULL,
[Old_Cust_AssetClassAlt_Key] [smallint] NULL,
[RefCustomerId] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NOT NULL,
[EffectiveToTimeKey] [int] NOT NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[MocStatus] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MocDate] [smalldatetime] NULL,
[MocTypeAlt_Key] [int] NULL
) ON [PRIMARY]
GO
