CREATE TABLE [DataUpload].[MocAccountDataUpload]
(
[Entitykey] [int] NOT NULL IDENTITY(1, 1),
[MocAccountDataEntityId] [int] NULL,
[CustomerID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerAcID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerName] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmountofWriteOff] [decimal] (18, 2) NULL,
[Balance] [decimal] (18, 2) NULL,
[UnservInterestAmt] [decimal] (18, 2) NULL,
[AdditionalProvision] [decimal] (6, 2) NULL,
[AdditionalProvisionAmount] [decimal] (18, 2) NULL,
[MOCReason] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[ScreenFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DataSource] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecuritizedAcc] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Restructured] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOCNature] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsDelete] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExistingFINALASSETCLASSALT_KEY] [int] NULL,
[ExistingBALANCE] [decimal] (18, 2) NULL,
[ExistingTOTALPROVISION] [decimal] (18, 2) NULL,
[NewFINALASSETCLASSALT_KEY] [int] NULL,
[NewBALANCE] [decimal] (18, 2) NULL,
[NewTOTALPROVISION] [decimal] (18, 2) NULL,
[CustomerEntityID] [int] NULL,
[AccountEntityid] [int] NULL
) ON [PRIMARY]
GO
