CREATE TABLE [DataUpload].[MocCustomerDataUpload]
(
[Entitykey] [int] NOT NULL IDENTITY(1, 1),
[MocCustomerDataEntityId] [int] NULL,
[CustomerID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerName] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SYSAssetClassification] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOCAssetClassification] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NPADate] [date] NULL,
[SecurityValue] [decimal] (18, 2) NULL,
[AdditionalProvision] [decimal] (18, 2) NULL,
[MOCReason] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[ScreenFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOCTYPE] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__MocCustom__MOCTY__3A6282ED] DEFAULT ('AUTO'),
[SystemCompSecurityVal] [decimal] (18, 2) NULL,
[MOCCompSecurityVal] [decimal] (18, 2) NULL,
[DataSource] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsDelete] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerEntityID] [int] NULL
) ON [PRIMARY]
GO
