CREATE TABLE [dbo].[RestrOutput_Old]
(
[CustomerID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerAcID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TypeOfRestructure] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Covid_Category] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RestructureDt] [date] NULL,
[Pre_Restr_AssetClass] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreRestructureNPA_Date] [date] NULL,
[Current_AssetClass] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrentNPA_Date] [date] NULL,
[DPD_Max] [int] NULL,
[DPD_Breach_Date] [date] NULL,
[ZeroDPD_Date] [date] NULL,
[Res_POS_to_CurrentPOS_Per] [decimal] (5, 2) NULL,
[RestructureStage] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetClass_On_Iinvocation] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProvPerOnRestrucure] [decimal] (5, 2) NULL,
[RestructurePOS] [decimal] (20, 2) NULL,
[CurrentPOS] [decimal] (20, 2) NULL,
[BALANCE] [decimal] (16, 2) NULL,
[PrincRepayStartDate] [date] NULL,
[InttRepayStartDate] [date] NULL,
[SP_ExpiryDate] [date] NULL,
[SP_ExpiryExtendedDate] [date] NULL,
[RestrProvPer] [decimal] (5, 2) NULL,
[ProvReleasePer] [decimal] (5, 2) NULL,
[AppliedNormalProvPer] [decimal] (5, 2) NULL,
[FinalProvPer] [decimal] (5, 2) NULL,
[PreDegProvPer] [decimal] (5, 2) NULL,
[UpgradeDate] [date] NULL,
[SurvPeriodEndDate] [date] NULL,
[DegDurSP_PeriodProvPer] [decimal] (5, 2) NULL,
[RestructureProvision] [decimal] (18, 2) NULL,
[RESTR_SecuredProvision] [decimal] (18, 2) NULL,
[RESTR_UnSecuredProvision] [decimal] (18, 2) NULL,
[RESTR_FlgDeg] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RESTR_FlgUpg] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecuredAmt] [decimal] (16, 2) NULL,
[UnSecuredAmt] [decimal] (16, 2) NULL,
[BankTotalProvision] [decimal] (16, 2) NULL,
[RBITotalProvision] [decimal] (18, 2) NULL,
[TotalProvision] [decimal] (16, 2) NULL,
[CreatedDate] [date] NULL
) ON [PRIMARY]
GO
