CREATE TABLE [dbo].[CollateralMgmtUpload_Mod]
(
[SrNo] [int] NULL,
[UploadID] [int] NULL,
[OldCollateralID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaggingLevel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Related_UCIC_CustomerID_AccountID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DistributionLevel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DistributionValue] [decimal] (16, 2) NULL,
[CollateralType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollateralSubType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollateralOwnerType] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollateralOwnershipType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChargeType] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChargeNature] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShareAvailableToBank] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShareValue] [decimal] (16, 2) NULL,
[CollateralValueSanctionRs] [decimal] (16, 2) NULL,
[CollateralValueNPADateRs] [decimal] (16, 2) NULL,
[CollateralValueLastReviewRs] [decimal] (16, 2) NULL,
[ValuationDate] [datetime] NULL,
[CurrentCollateralValueRs] [decimal] (16, 2) NULL,
[ExpiryBusinessRule] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[AuthorisationStatus] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Changes] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Remark] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [datetime] NULL,
[ModifiedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [datetime] NULL,
[ApprovedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [datetime] NULL,
[CollateralID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
