CREATE TABLE [dbo].[CalypsoInvMOC_ChangeDetails]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[MOCType_Flag] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerEntityID] [int] NULL,
[AccountEntityID] [int] NULL,
[AssetClassAlt_Key] [int] NULL,
[NPA_Date] [date] NULL,
[AddlProvPer] [decimal] (5, 2) NULL,
[AddlProvAbs] [decimal] (16, 2) NULL,
[CurntQtrRv] [decimal] (16, 2) NULL,
[PrincOutStd] [decimal] (16, 2) NULL,
[unserviedint] [decimal] (16, 2) NULL,
[FlgRestructure] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RestructureDate] [date] NULL,
[FlgFITL] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DFVAmt] [decimal] (16, 2) NULL,
[RePossession] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RepossessionDate] [date] NULL,
[WeakAccount] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WeakAccountDate] [date] NULL,
[Sarfaesi] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SarfaesiDate] [date] NULL,
[FlgUnusualBounce] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnusualBounceDate] [date] NULL,
[FlgUnClearedEffect] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnClearedEffectDate] [date] NULL,
[FlgFraud] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FraudDate] [date] NULL,
[BenamiLoansFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MarkBenamiDate] [date] NULL,
[SubLendingFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MarkSubLendingDate] [date] NULL,
[AbscondingFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MarkAbscondingDate] [date] NULL,
[TwoFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TwoDate] [date] NULL,
[MOC_ExpireDate] [date] NULL,
[MOC_Reason] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOC_Date] [date] NULL,
[MOC_By] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOC_Source] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [datetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [datetime] NULL,
[ApprovedByFirstLevel] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApprovedFirstLevel] [datetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [datetime] NULL,
[MOCTYPE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TwoAmount] [decimal] (18, 2) NULL,
[MOCProcessed] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BookValue] [decimal] (18, 2) NULL,
[SMADate] [datetime] NULL,
[SMASubAssetClassValue] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UCICID] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
