CREATE TABLE [dbo].[CollateralOtherOwner]
(
[Entity_Key] [int] NOT NULL IDENTITY(1, 1),
[CollateralID] [int] NULL,
[CustomeroftheBankAlt_Key] [int] NULL,
[AccountID] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherOwnerName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAN] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherOwnerRelationshipAlt_Key] [int] NULL,
[IfRelationselectAlt_Key] [int] NULL,
[AddressType] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Company] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressLine1] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressLine2] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressLine3] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PinCode] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[District] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STDCodeO] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhoneNumberO] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STDCodeR] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhoneNumberR] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FaxNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MobileNO] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[AuthorisationStatus] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [datetime] NULL,
[ModifiedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [datetime] NULL,
[ApprovedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [datetime] NULL
) ON [PRIMARY]
GO
