CREATE TABLE [dbo].[SysReportformat]
(
[SrNo] [int] NOT NULL,
[BankName] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankNameFontSize] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankNameFontFamily] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankNameFontStyle] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankNameFontWeight] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankNameColour] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankAddress] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankAddFontSize] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankAddFontFamilly] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankAddFontStyle] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankAddFontWeight] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankAddFontColour] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportNameFontSize] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportNameFontFamilly] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportNameFontStyle] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportNameFontWeight] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportNameFontColour] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeadFontSize] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeadFontFamily] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeadFontStyle] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeadFontWeight] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeadColour] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeadBGColour] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BodyFontSize] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BodyFontFamily] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BodyFontStyle] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BodyFontWeight] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BodyColour] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BodyBGcolour] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GrantTotalFontSize] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GrantFontFamily] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GrantFontStyle] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GrantFontWeight] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GrantColour] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GrantBGcolour] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tier] [smallint] NULL,
[BranchLbl] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RegionLbl] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZoneLbl] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankLbl] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmountIn] [int] NULL,
[ReportPathName] [bit] NULL,
[HindiFont] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HindiFontFamily] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HindiFontStyle] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HindiFontWeight] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchTotal] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RegionTotal] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZoneTotal] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankTotal] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerName] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[D2KName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FooterFontFamily] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FooterFontSize] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FooterFontStyle] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FooterFontWeight] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeaderDetailFontFamily] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeaderDetailFontSize] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeaderDetailFontStyle] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeaderDetailFontWeight] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FormatG] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FormatF] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ImagePath] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankNameHindi] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankAddressHindi] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankAlt_Key] [smallint] NULL,
[RBIBankCode] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Active] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchVisibility] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RegionVisibility] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZoneVisibility] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankVisibility] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
