CREATE TABLE [dbo].[SMA_26122021_NEW]
(
[CurrentProcessingDate] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrNo] [bigint] NULL,
[SourceName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceSystemCustomerID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UCIF_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerAcID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PANNO] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerName] [varchar] (225) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustSegmentCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FacilityType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductName] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActSegmentCode] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SchemeType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Balance] [decimal] (16, 2) NOT NULL,
[PrincOutStd] [decimal] (18, 2) NOT NULL,
[PrincOverdue] [decimal] (18, 2) NOT NULL,
[IntOverdue] [decimal] (18, 2) NOT NULL,
[OtherOverdue] [decimal] (18, 2) NOT NULL,
[OverdueAmt] [decimal] (18, 2) NOT NULL,
[CurrentLimit] [decimal] (16, 2) NOT NULL,
[ContiExcessDt] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StockStDt] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastCrDate] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntNotServicedDt] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverDueSinceDt] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReviewDueDt] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DPD_StockStmt] [int] NULL,
[DPD_NoCredit] [int] NULL,
[DPD_IntService] [int] NULL,
[DPD_Overdrawn] [int] NULL,
[DPD_Overdue] [int] NULL,
[DPD_Renewal] [int] NULL,
[SMA_DPD] [int] NULL,
[AccountFlgSMA] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountSMA_Dt] [date] NULL,
[AccountSMA_AssetClass] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMA_Reason] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DPD_UCIF_ID] [int] NULL,
[UCICFlgSMA] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UCICSMA_Dt] [date] NULL,
[UCICSMA_AssetStatus] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MovementFromDate] [date] NULL,
[MovementFromStatus] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MovementToStatus] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
