CREATE TABLE [dbo].[InterestGaurav]
(
[Report Date] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UCIC] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIF ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Borrower Name] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Branch Code] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Branch Name] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account No ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Source System Facility] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scheme Type] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scheme Code] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scheme Description] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Seg Code] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Segment Description] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Segment] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account DPD] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NPA Date] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Outstanding] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Principal Outstanding] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Asset Classification] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Soirce System Status] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[interest Dues] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Penal Dues] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Other Dues] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[interest accured but not due] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[penal accured but not due] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Credit Card interest Outstanding] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Credit Card other charges] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Credit Card GST ST Outstanding] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Interest Dividend on Bond Debentures] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
