CREATE TABLE [dbo].[advacbasicdetail_12022022]
(
[Ac_Key] [bigint] NOT NULL,
[BranchCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AccountEntityId] [int] NOT NULL,
[CustomerEntityId] [int] NOT NULL,
[SystemACID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerACID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GLAlt_Key] [int] NULL,
[ProductAlt_Key] [smallint] NULL,
[GLProductAlt_Key] [smallint] NULL,
[FacilityType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SectorAlt_Key] [smallint] NULL,
[SubSectorAlt_Key] [smallint] NULL,
[ActivityAlt_Key] [smallint] NULL,
[IndustryAlt_Key] [smallint] NULL,
[SchemeAlt_Key] [smallint] NULL,
[DistrictAlt_Key] [smallint] NULL,
[AreaAlt_Key] [smallint] NULL,
[VillageAlt_Key] [int] NULL,
[StateAlt_Key] [smallint] NULL,
[CurrencyAlt_Key] [smallint] NULL,
[OriginalSanctionAuthAlt_Key] [smallint] NULL,
[OriginalLimitRefNo] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalLimit] [decimal] (16, 2) NULL,
[OriginalLimitDt] [date] NULL,
[DtofFirstDisb] [date] NULL,
[FlagReliefWavier] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnderLineActivityAlt_Key] [smallint] NULL,
[MicroCredit] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[segmentcode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ScrCrError] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdjDt] [date] NULL,
[AdjReasonAlt_Key] [smallint] NULL,
[MarginType] [smallint] NULL,
[Pref_InttRate] [decimal] (4, 2) NULL,
[CurrentLimitRefNo] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GuaranteeCoverAlt_Key] [smallint] NULL,
[AccountName] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetClass] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JointAccount] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastDisbDt] [date] NULL,
[ScrCrErrorBackup] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountOpenDate] [date] NULL,
[Ac_LADDt] [date] NULL,
[Ac_DocumentDt] [date] NULL,
[CurrentLimit] [decimal] (16, 2) NULL,
[InttTypeAlt_Key] [smallint] NULL,
[InttRateLoadFactor] [decimal] (4, 2) NULL,
[Margin] [decimal] (5, 2) NULL,
[CurrentLimitDt] [date] NULL,
[Ac_DueDt] [date] NULL,
[DrawingPowerAlt_Key] [smallint] NULL,
[RefCustomerId] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NOT NULL,
[EffectiveToTimeKey] [int] NOT NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [datetime] NOT NULL,
[MocStatus] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MocDate] [smalldatetime] NULL,
[MocTypeAlt_Key] [int] NULL,
[IsLAD] [bit] NULL,
[FincaleBasedIndustryAlt_key] [smallint] NULL,
[AcCategoryAlt_Key] [smallint] NULL,
[OriginalSanctionAuthLevelAlt_Key] [smallint] NULL,
[AcTypeAlt_Key] [smallint] NULL,
[ScrCrErrorSeq] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BSRUNID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdditionalProv] [decimal] (16, 2) NULL,
[AclattestDevelopment] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceAlt_Key] [tinyint] NULL,
[LoanSeries] [smallint] NULL,
[LoanRefNo] [smallint] NULL,
[SecuritizationCode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Full_Disb] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalBranchcode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProjectCost] [decimal] (16, 2) NULL,
[FlgSecured] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferencePeriod] [smallint] NULL
) ON [PRIMARY]
GO
