CREATE TABLE [dbo].[TWO_653]
(
[Report date] [datetime] NULL,
[UCIC] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIF ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Borrower Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Branch Code] [float] NULL,
[Branch Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account No#] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Source System] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Facility] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scheme Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scheme Code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scheme Description] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Seg Code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AcBuSegmentDescription] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Facility_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opening Balance] [float] NULL,
[Addition] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Increase In Balance] [float] NULL,
[Cash Recovery] [float] NULL,
[Recovery from NPA Sale] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Closing Balance] [float] NULL,
[Write-off] [float] NULL,
[DPD_Max] [float] NULL,
[NPA Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Asset Classification] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Host System] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AcBuRevisedSegmentCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NPA date1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Days from NPA] [float] NULL,
[Assets Class ] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Processing Date ] [datetime] NULL
) ON [PRIMARY]
GO
