CREATE TABLE [dbo].[AdvAcRestructureDetail_08072022]
(
[EntityKey] [bigint] NOT NULL IDENTITY(1, 1),
[AccountEntityId] [int] NULL,
[RestructureTypeAlt_Key] [smallint] NULL,
[RestructureCatgAlt_Key] [smallint] NULL,
[RestructureProposalDt] [date] NULL,
[RestructureAmt] [decimal] (18, 0) NULL,
[RestructureApprovalDt] [date] NULL,
[RestructureSequenceRefNo] [int] NULL,
[DiminutionAmount] [decimal] (18, 0) NULL,
[RestructureByAlt_Key] [int] NULL,
[RefCustomerId] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefSystemAcId] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[CDRFlg] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExitCDRFlg] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CutOffDate] [date] NULL,
[RestructureReason] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverDueSinceDt] [date] NULL,
[BankApprovalDt] [date] NULL,
[ForwardDt] [date] NULL,
[Remark] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SDR_INVOKED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SDR_REFER_DATE] [date] NULL,
[PreRestrucDefaultDate] [datetime] NULL,
[PreRestrucAssetClass] [int] NULL,
[PostRestrucAssetClass] [int] NULL,
[InvocationDate] [datetime] NULL,
[ConversionDate] [datetime] NULL,
[CRILIC_Fst_DefaultDate] [datetime] NULL,
[FstDefaultReportingBank] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICA_SignDate] [datetime] NULL,
[CreditProvision] [decimal] (16, 2) NULL,
[DFVProvision] [decimal] (16, 2) NULL,
[MTMProvision] [decimal] (16, 2) NULL,
[DisbursementDate] [date] NULL,
[RestructurePOS] [decimal] (16, 2) NULL,
[SP_ExpiryDate] [date] NULL,
[FlgPUI] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NEW_SP_PERIOD_EXP_DATE] [date] NULL,
[RESTR_STATUS] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POST_DEG_DEFAULT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POST_DEG_DEFAULT_DATE] [date] NULL,
[DEFAULT_IN_MONITORING_PERIOD] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POST_RESTR_UPG_DATE] [date] NULL,
[DPD_AsOnRestr] [smallint] NULL,
[SLBC_Restructuring] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Restructure_NPA_Dt] [date] NULL,
[RestructureDt] [date] NULL,
[BankingRelationTypeAlt_Key] [int] NULL,
[EquityConversionYN] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrincRepayStartDate] [date] NULL,
[InttRepayStartDate] [datetime] NULL,
[PreRestructureAssetClassAlt_Key] [int] NULL,
[PreRestructureNPA_Date] [datetime] NULL,
[COVID_OTR_CatgAlt_Key] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RestructureApprovingAuthority] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvestmentGrade] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlgMorat] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreRestructureNPA_Prov] [decimal] (16, 2) NULL,
[AssetClassAlt_KeyOnInvocation] [smallint] NULL,
[ProvPerOnRestrucure] [decimal] (5, 2) NULL,
[DPD_AsOnRestructure] [smallint] NULL,
[DPD_Breach_Date] [date] NULL,
[ZeroDPD_Date] [date] NULL,
[PreDegProvPer] [decimal] (5, 2) NULL,
[UpgradeDate] [date] NULL,
[SurvPeriodEndDate] [date] NULL,
[RestructureStage] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POS_10PerPaidDate] [date] NULL,
[RestructureFacilityTypeAlt_Key] [smallint] NULL,
[SP_ExpiryExtendedDate] [date] NULL,
[RestructreTOS] [decimal] (20, 2) NULL,
[UnserviceInttAsOnRestructure] [decimal] (20, 2) NULL,
[RestructureStatus] [smallint] NULL,
[RestructureFailureDate] [date] NULL
) ON [PRIMARY]
GO
