CREATE TABLE [dbo].[DimGL_Mod]
(
[GL_Key] [smallint] NOT NULL IDENTITY(1, 1),
[GLAlt_Key] [smallint] NOT NULL,
[GLCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GLName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GLShortName] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GLShortNameEnum] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GLGroupType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GLGroupAlt_Key] [int] NULL,
[GLGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GLSubGroupAlt_Key] [int] NULL,
[GLSubGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GLSegmentAlt_Key] [int] NULL,
[GLSegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GLSubSegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GLValidCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AbstractCat] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AbstractCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AbstractDescription] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdvRefGLAlt_key] [int] NULL,
[BsDescription] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BsSchedule] [smallint] NULL,
[BsScheduleDescription] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ComputationBusinessLogic] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WeeklyCode] [int] NULL,
[WeeklyDescription] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LfCode] [int] NULL,
[LfDescription] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Schd_Head_No] [int] NULL,
[Schd_No] [int] NULL,
[Sub_Schd_No] [int] NULL,
[Sub_Sub_Schd_No] [int] NULL,
[SrcSysGLCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysGLName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestSysGLCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GLCode2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GLName2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[ChangeFields] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
