CREATE TABLE [dbo].[CalypsoAccountLevelPostMOC]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[AccountEntityID] [int] NULL,
[AccountID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POS] [decimal] (18, 2) NULL,
[InterestReceivable] [decimal] (18, 2) NULL,
[RestructureFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RestructureDate] [date] NULL,
[FITLFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DFVAmount] [decimal] (16, 2) NULL,
[RePossessionFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RePossessionDate] [date] NULL,
[InherentWeaknessFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InherentWeaknessDate] [date] NULL,
[SARFAESIFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SARFAESIDate] [date] NULL,
[UnusualBounceFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnusualBounceDate] [date] NULL,
[UnclearedEffectsFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnclearedEffectsDate] [date] NULL,
[AdditionalProvisionCustomerlevel] [decimal] (16, 2) NULL,
[AdditionalProvisionAbsolute] [decimal] (16, 2) NULL,
[MOCReason] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [datetime] NULL,
[ModifyBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [date] NULL,
[ApprovedBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [date] NULL,
[MOCDate] [date] NULL,
[MOCBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOCSource] [int] NULL,
[FraudAccountFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FraudDate] [date] NULL,
[ScreenFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
