CREATE TABLE [dbo].[AdvCustRelationship_Mod]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[CustomerEntityId] [int] NULL,
[RelationEntityId] [int] NULL,
[SalutationAlt_Key] [smallint] NULL,
[Name] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConstitutionAlt_Key] [smallint] NULL,
[OccupationAlt_Key] [smallint] NULL,
[ReligionAlt_Key] [smallint] NULL,
[CasteAlt_Key] [smallint] NULL,
[FarmerCatAlt_Key] [smallint] NULL,
[MaritalStatusAlt_Key] [smallint] NULL,
[NetWorth] [decimal] (16, 2) NULL,
[DateofBirth] [date] NULL,
[Qualification1Alt_Key] [smallint] NULL,
[Qualification2Alt_Key] [smallint] NULL,
[Qualification3Alt_Key] [smallint] NULL,
[Qualification4Alt_Key] [smallint] NULL,
[MobileNo] [varchar] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VoterID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RationCardNo] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AadhaarId] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NPR_Id] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PassportNo] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PassportIssueDt] [date] NULL,
[PassportExpiryDt] [date] NULL,
[PassportIssueLocation] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DL_No] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DL_IssueDate] [date] NULL,
[DL_ExpiryDate] [date] NULL,
[DL_IssueLocation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusiEntity_NationalityTypeAlt_Key] [smallint] NULL,
[NationalityCountryAlt_Key] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAN] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAN] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIN] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RegistrationNo] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIN] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIN] [varchar] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServiceTax] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherIdType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RegistrationAuth] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RegistrationAuthLocation] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrevFinYearSales] [decimal] (16, 2) NULL,
[EmployeeCount] [int] NULL,
[SalesFigFinYr] [date] NULL,
[Designation_ContactPeroson] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncorporationDate] [date] NULL,
[BusinessCategoryAlt_Key] [smallint] NULL,
[BusinessIndustryTypeAlt_Key] [smallint] NULL,
[SharePercent] [decimal] (16, 2) NULL,
[RetirementDate] [date] NULL,
[ProfessionArea] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExistingCustomer] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ScrCrError] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefCustomerId] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[CIBILPGId] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Initial] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BecomNRI_Dt] [date] NULL,
[AuthSignStartDt] [date] NULL,
[AuthSignEndDt] [date] NULL,
[ScrCrErrorSeq] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NetWorthDate] [date] NULL,
[AdvNetWorth] [decimal] (16, 2) NULL,
[DefendentExpire] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefendentExpireDt] [date] NULL,
[PPhoto] [varbinary] (max) NULL,
[PPhotoDt] [date] NULL,
[PPhotoURL] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChangeFields] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActionStatus] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DirectorDebarred] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LEI] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
