CREATE TABLE [dbo].[project]
(
[Customer_ID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer_Name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account_ID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Project_Category] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Project_Sub_Category] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Project_Ownership] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Project_Authority] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Original_DCCO] [date] NULL,
[Original_Project_cost] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Original_Debt] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Revised_DCCO] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Initial_Extenstion] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Beyond_control_of_Promoters] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Court_Case_Arbitration] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Change_in_Ownership] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIO_Reference_date] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIO_DCCO] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Change_in_Project_Scope] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fresh_Original_DCCO] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cost_Overrun] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cost_overrun Finance by Bank] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cost_Overrun_Per] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Revised_Project cost] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Revised_Debt] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Takeout_finance] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Asset_class_Sellers_book] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Npa_Date_Sellers_book] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Restructuring] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Current_Asset_Class] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NPA_Date] [date] NULL,
[Actual_DCCO] [date] NULL,
[RM_Credit_officer] [varchar] (225) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
