CREATE TABLE [dbo].[STD_ProvDetail_PROD]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[DataDate] [date] NULL,
[TerritoryAlt_Key] [smallint] NULL,
[SourceAlt_Key] [smallint] NULL,
[GL_Code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GLProductAlt_Key] [smallint] NULL,
[CustomerID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerEntityID] [int] NULL,
[CustomerName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerAcId] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SystemAcId] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountEntityID] [int] NULL,
[InitialAssetClassAlt_Key] [int] NULL,
[FinalAssetClassAlt_Key] [int] NULL,
[SanctionDate] [date] NULL,
[FacilityType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdvType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IndustryCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Balance] [decimal] (24, 2) NULL,
[OrgProvisionAlt_Key] [smallint] NULL,
[ProvisionAlt_Key] [smallint] NULL,
[FinalProvCatSetId] [int] NULL,
[TotalAdjAmt] [decimal] (24, 2) NULL,
[NetAmt] [decimal] (24, 2) NULL,
[TotalExclAmt] [decimal] (18, 2) NULL,
[NetAmtForProv] [decimal] (24, 2) NULL,
[FinalProvPer] [decimal] (5, 2) NULL,
[GovtGtyAmt] [decimal] (18, 2) NULL,
[DFVAmt] [decimal] (18, 2) NULL,
[SecurityValue] [decimal] (18, 2) NULL,
[ApprRV] [decimal] (18, 2) NULL,
[SecuredAmt] [decimal] (18, 2) NULL,
[UnSecuredAmt] [decimal] (18, 2) NULL,
[CoverGovGur] [decimal] (18, 2) NULL,
[ProvSecured] [decimal] (18, 2) NULL,
[ProvUnsecured] [decimal] (18, 2) NULL,
[ProvCoverGovGur] [decimal] (18, 2) NULL,
[AddlProvision] [decimal] (18, 2) NULL,
[TotalProvision] [decimal] (18, 2) NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[UploadCatFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExpireStatus] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AcsegDesc] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Acseg] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalBal] [decimal] (22, 2) NULL,
[ProcessingStatus] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sch9_ProcessingStatus] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOCSTATUS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCH9_Freeze_Flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[APPROP_GOV_GTY] [decimal] (24, 2) NULL,
[SCH9_ADJAMT] [decimal] (24, 2) NULL,
[SCH9_NETAMT] [decimal] (24, 2) NULL,
[SECTORSHORTNAME] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FITL_Provision] [decimal] (24, 2) NULL,
[FITL_PROV_SECU] [decimal] (24, 2) NULL,
[FITL_PROV_UNSECU] [decimal] (24, 2) NULL,
[FITL_PROV_GOVGUR] [decimal] (24, 2) NULL,
[DFV_Provision] [decimal] (24, 2) NULL,
[DFV_PROV_SECU] [decimal] (24, 2) NULL,
[DFV_PROV_UNSECU] [decimal] (24, 2) NULL,
[DFV_PROV_GOVGUR] [decimal] (24, 2) NULL,
[AdjCategoryAlt_Key] [int] NULL,
[SubSectorAlt_Key] [int] NULL,
[OriginalAdjBal] [decimal] (24, 2) NULL
) ON [PRIMARY]
GO
