CREATE TABLE [dbo].[AdvAcProjectDetail]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[CustomerEntityID] [int] NULL,
[RefAccountEntityId] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ProjectId] [int] NULL,
[ProjectName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProjectCatgAlt_Key] [smallint] NULL,
[FinancialClosureDt] [date] NULL,
[PaidupCapital] [numeric] (18, 0) NULL,
[ProjectParticular] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalEnvisagCompletionDt] [date] NULL,
[RevisedCompletionDt] [date] NULL,
[ActualCompletionDt] [date] NULL,
[ProjectCostByInternalSource] [decimal] (14, 2) NULL,
[ProjectCostByDebt] [decimal] (14, 2) NULL,
[ProjectCostByEquity] [decimal] (14, 2) NULL,
[ProjectCostByOtherMeans] [decimal] (14, 2) NULL,
[ProjectCostByPPEquity] [decimal] (14, 2) NULL,
[ProjectCostByPPDebt] [decimal] (14, 2) NULL,
[ProjCostUptoPrevFinYear] [decimal] (14, 2) NULL,
[ProjCostCurFinYear] [decimal] (14, 2) NULL,
[ProjCostNextYear1] [decimal] (14, 2) NULL,
[ProjCostNextYear2] [decimal] (14, 2) NULL,
[ProjCostNextYear3] [decimal] (14, 2) NULL,
[ProjCostNextYear4] [decimal] (14, 2) NULL,
[ProjCostNextYear5] [decimal] (14, 2) NULL,
[ProjCostBeyond5Year] [decimal] (14, 2) NULL,
[ProjectCostRevisedByInternalSource] [decimal] (14, 2) NULL,
[ProjectCostRevisedByDebt] [decimal] (14, 2) NULL,
[ProjectCostRevisedByEquity] [decimal] (14, 2) NULL,
[ProjectCostRevisedByOtherMeans] [decimal] (14, 2) NULL,
[ProjectCurrentStatus] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REVProjCostUptoPrevFinYear] [decimal] (14, 2) NULL,
[REVProjCostCurFinYear] [decimal] (14, 2) NULL,
[REVProjCostNextYear1] [decimal] (14, 2) NULL,
[REVProjCostNextYear2] [decimal] (14, 2) NULL,
[REVProjCostNextYear3] [decimal] (14, 2) NULL,
[REVProjCostNextYear4] [decimal] (14, 2) NULL,
[REVProjCostNextYear5] [decimal] (14, 2) NULL,
[REVProjCostBeyond5Year] [decimal] (14, 2) NULL,
[RevProjectCostByPPEquity] [decimal] (14, 2) NULL,
[RevProjectCostByPPDebt] [decimal] (14, 2) NULL,
[RefSystemacid] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NOT NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[MocStatus] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MocDate] [smalldatetime] NULL,
[MocTypeAlt_Key] [int] NULL,
[CustomerId] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountId] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProjectDelReason_AltKey] [int] NULL,
[StandardRestruct_Altkey] [int] NULL
) ON [PRIMARY]
GO
