CREATE TABLE [dbo].[DPD]
(
[CustomerACID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountEntityid] [int] NOT NULL,
[SourceSystemCustomerID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntNotServicedDt] [date] NULL,
[Process_Date] [date] NULL,
[LastCrDate] [date] NULL,
[ContiExcessDt] [date] NULL,
[OverDueSinceDt] [date] NULL,
[ReviewDueDt] [date] NULL,
[StockStDt] [date] NULL,
[PrincOverdueSinceDt] [date] NULL,
[IntOverdueSinceDt] [date] NULL,
[OtherOverdueSinceDt] [date] NULL,
[RefPeriodIntService] [smallint] NULL,
[RefPeriodNoCredit] [smallint] NULL,
[RefPeriodOverDrawn] [smallint] NULL,
[RefPeriodOverdue] [smallint] NULL,
[RefPeriodReview] [smallint] NULL,
[RefPeriodStkStatement] [smallint] NULL,
[DegDate] [date] NULL,
[EffectiveFromTimeKey] [int] NOT NULL,
[EffectiveToTimeKey] [int] NOT NULL,
[DPD_IntService] [int] NULL,
[DPD_NoCredit] [int] NULL,
[DPD_Overdrawn] [int] NULL,
[DPD_Overdue] [int] NULL,
[DPD_Renewal] [int] NULL,
[DPD_StockStmt] [int] NULL,
[DPD_PrincOverdue] [int] NULL,
[DPD_IntOverdueSince] [int] NULL,
[DPD_OtherOverdueSince] [int] NULL,
[DPD_MAX] [int] NULL
) ON [PRIMARY]
GO
