CREATE TABLE [dbo].[BuyoutFinalDetails_01112022]
(
[Entity_Key] [int] NOT NULL IDENTITY(1, 1),
[SummaryID] [int] NULL,
[SlNo] [int] NULL,
[AUNo] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PoolName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Category] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BuyoutPartyLoanNo] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAN] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AadharNo] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrincipalOutstanding] [decimal] (18, 2) NULL,
[InterestReceivable] [decimal] (18, 2) NULL,
[Charges] [decimal] (18, 2) NULL,
[AccuredInterest] [decimal] (18, 2) NULL,
[DPD] [int] NULL,
[AssetClass] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Changes] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Remark] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [date] NULL,
[ModifyBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [date] NULL,
[ApprovedBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [date] NULL,
[SecurityValue] [decimal] (18, 2) NULL,
[FinalNpaDt] [date] NULL,
[FinalAssetClassAlt_Key] [smallint] NULL,
[ProvisionAlt_Key] [smallint] NULL,
[NetBalance] [decimal] (18, 2) NULL,
[ApprRV] [decimal] (18, 2) NULL,
[SecuredAmt] [decimal] (18, 2) NULL,
[UnSecuredAmt] [decimal] (18, 2) NULL,
[UsedRV] [decimal] (18, 2) NULL,
[Provsecured] [decimal] (18, 2) NULL,
[ProvUnsecured] [decimal] (18, 2) NULL,
[TotalProvision] [decimal] (18, 2) NULL,
[FLGDEG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FLGUPG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DegReason] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpgDate] [date] NULL,
[PrevProvPercentage] [decimal] (16, 2) NULL,
[FinalProvPercentage] [decimal] (16, 2) NULL,
[Action] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
