CREATE TABLE [dbo].[MetaScreenFieldDetail_21042022]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[MenuId] [smallint] NULL,
[ScreenName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CtrlName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ResourceKey] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FldDataType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Col_lg] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Col_md] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Col_sm] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MinLength] [smallint] NULL,
[MaxLength] [smallint] NULL,
[ErrorCheck] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DataSeq] [smallint] NULL,
[FldGridView] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CriticalErrorType] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ScreenFieldNo] [int] NULL,
[IsEditable] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsVisible] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsUpper] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsMandatory] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllowChar] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DisAllowChar] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefaultValue] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllowToolTip] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferenceColumnName] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferenceTableName] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOC_Flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [datetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [datetime] NULL,
[ScreenFieldGroup] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HigherLevelEdit] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ApplicableForWorkFlow] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsExtractedEditable] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsMocVisible] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
