CREATE TABLE [dbo].[DimActivityMapping]
(
[ActivityAlt_Key] [smallint] NOT NULL,
[ActivityName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActivityShortName] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActivityShortNameEnum] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActivityGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActivitySubGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActivitySegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActivityValidCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IndustryAlt_Key] [smallint] NULL,
[BSR1Acode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BSR1Bcode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FoodPro] [smallint] NULL,
[ActivityLBRCode] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetClass] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BSR3code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIBIL_ConsumerAcType] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ComodityCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SectorLBRCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SickIndustryCode] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SickSSIIndAlt_Key] [smallint] NULL,
[AssetClassNorm] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherAssets] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MinorActivity] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHGActivity] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prod] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inv] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NF] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Act_Type] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LBRGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LBRSubGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LBRCode] [smallint] NULL,
[Act_PH] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIBILBusinessIndustryType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SICCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActivitySubGroupDescription] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Intrest_Freq] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysActivityCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysActivityCode1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysActivityName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysActivityName1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestSysActivityCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModifie] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[VCI] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IRBMark] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EWSIndustryAlt_Key] [smallint] NULL,
[BSEIndustryAlt_Key] [smallint] NULL,
[EWSKeySectorAlt_Key] [int] NULL,
[NewActivitySegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Allied_Agr] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceAlt_Key] [int] NULL,
[ActivityMappingAlt_Key] [int] NULL,
[Activity_Key] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
