CREATE TABLE [dbo].[SysReportDirectory_1403]
(
[SeqNo] [smallint] NULL,
[ReportID] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportRdlName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportUrl] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VersionNo] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Remark] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeploymentDt] [date] NULL,
[Frequency_Period] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Deploy] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Deploy_Prod] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportMenuId] [int] NULL,
[ReportRdlFullName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportFieldDisplay] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeptReportNo] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RBI_ReportNo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRisMacReportNo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportFrequency_Key] [smallint] NULL,
[ReportingDay] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportOwnerMain] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportOwnerAlternate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubmissionType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstReportGenerationDate] [date] NULL,
[NextEntityCreationDate] [date] NULL,
[DaysToGenerate] [smallint] NULL,
[AdvReminderInDays] [smallint] NULL,
[AdvReminderRecipient] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdvReminderCopyTo] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdvReminderSubject] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdvReminderText] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reminder1_InDays] [smallint] NULL,
[Reminder1_Recipient] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reminder1_CopyTo] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reminder1_Subject] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reminder1_Text] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reminder2_InDays] [smallint] NULL,
[Reminder2_Recipient] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reminder2_CopyTo] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reminder2_Subject] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reminder2_Text] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RBI_Recipient] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RBI_CopyTo] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RBI_Subject] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RBI_Text] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Monitoring_Required] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ch_RptFrequency_EffectiveDate] [date] NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifyBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[ExportReportId] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExportReportName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeptGroupId] [smallint] NULL,
[PreMoc] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReqCommonSelecton] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
