CREATE TABLE [dbo].[RestructureAsset_Upload_Mod]
(
[AccountID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountEntityID] [int] NULL,
[UploadID] [int] NULL,
[RestructureFacility] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RevisedBusinessSeg] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DisbursementDate] [date] NULL,
[ReferenceDate] [date] NULL,
[InvocationDate] [date] NULL,
[DateofConversionintoEquity] [date] NULL,
[PrinRpymntStartDate] [date] NULL,
[InttRpymntStartDate] [date] NULL,
[AssetClassatRstrctr] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IfNPANPADate] [date] NULL,
[NPAQuarter] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TypeofRestructuring] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CovidMoratoriamMSME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CovidOTRCategory] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankingRelationship] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateofRestructuring] [date] NULL,
[RestructuringApprovingAuth] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateofIstDefaultonCRILIC] [date] NULL,
[ReportingBank] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateofSigningICA] [date] NULL,
[InvestmentGrade] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditProvisionRs] [decimal] (18, 2) NULL,
[DFVProvisionRs] [decimal] (18, 2) NULL,
[MTMProvisionRs] [decimal] (18, 2) NULL,
[SheetName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[SrNo] [int] NULL,
[OSasonDateofRstrctr] [decimal] (18, 2) NULL,
[POSasonDateofRstrctr] [decimal] (18, 2) NULL,
[approvedbyfirstlevel] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApprovedByFirstLevel] [date] NULL,
[EquityConversion] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StatusOfSpecificPeriod] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
