CREATE TABLE [dbo].[ReversefeedCalypso]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[CalypsoRFEntityID] [int] NULL,
[Date_of_data] [date] NULL,
[source_system_name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[branch_code] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ucic_id] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[issuerId] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[issuuerName] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ref_Txn_Sys_Cust_ID] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAN] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISSUER_CATEGORY_CODE] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GrpEntityOfBank] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CP_HOLIDAY] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CP_EXTERNAL_REF] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CP_FINANCIAL] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CP_PARENT] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CP_COMMENT] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CP_STATUS] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTERPARTY_SHORTNAME] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTERPARTY_FULLNAME] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTERPARTY_ROLE1] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTERPARTY_COUNTRY] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTERPARTY_ROLE2] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTERPARTY_ROLE3] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTERPARTY_ROLE4] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTERPARTY_ROLE5] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIF_ID] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ENPA_ASSET_CODE] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ENPA_DESCRIPTION] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ENPA_ASSET_CODE_DATE] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ENPA_D2K_NPA_DATE] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[IsChanged] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
