CREATE TABLE [dbo].[RBL_PUI_DATA]
(
[Customer ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Project Category] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Project Sub Category] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Project Ownership] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Project Authority] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Original DCCO] [datetime] NULL,
[Original Project cost] [float] NULL,
[Original Debt] [float] NULL,
[Revised DCCO] [datetime] NULL,
[Initial Extenstion] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Beyond control of Promoters] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Court Case Arbitration] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Change in Ownership ] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIO Reference date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIO_DCCO] [datetime] NULL,
[Change in Project Scope] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fresh Original DCCO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cost Overrun] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cost overrun Finance by Bank] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cost Overrun Per] [float] NULL,
[Revised Project cost] [float] NULL,
[Revised Debt] [float] NULL,
[Takeout finance] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Asset class in Sellers book] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Npa Date in Sellers book] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Restructuring] [datetime] NULL,
[Current Asset Class] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NPA Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual DCCO] [datetime] NULL,
[RM_Credit officer] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
