CREATE TABLE [dbo].[InvestCDIssuenotused]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[BranchCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISIN_No] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FaceValue] [decimal] (16, 2) NULL,
[DiscountedValue] [decimal] (16, 2) NULL,
[IssueDt] [date] NULL,
[MaturityDt] [date] NULL,
[IssuedFormat] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Benchmark] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DepositoryName] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OfferAmount] [decimal] (16, 2) NULL,
[UnitsIssued] [int] NULL,
[EffectiveInttRate] [decimal] (5, 2) NULL,
[MaturityDays] [smallint] NULL,
[Spread] [decimal] (5, 2) NULL,
[UnitPrice] [numeric] (6, 0) NULL,
[CouponTypeAlt_Key] [smallint] NULL,
[Series] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CDIssue_ID] [smallint] NULL,
[TimeKey] [int] NULL,
[DelSta] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[IssuedTo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
