CREATE TABLE [dbo].[DimState]
(
[State_Key] [smallint] NOT NULL,
[StateAlt_Key] [smallint] NOT NULL,
[StateAlt2_Key] [smallint] NOT NULL,
[StateName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[StateShortName] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateShortNameEnum] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateSubGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateSegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateValidCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TerritoryAlt_Key] [smallint] NOT NULL,
[TerritoryName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CibilCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PINCode] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RBICode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIBIL_COMM_CODE] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCAStateCode] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OfficialLanguageCatg] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysStateCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysStateName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestSysStateCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifyBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL
) ON [PRIMARY]
GO
