CREATE TABLE [dbo].[DimCollateralSecurityMapping]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[SecurityMappingAlt_Key] [int] NULL,
[SecurityAlt_Key] [int] NULL,
[SourceAlt_Key] [int] NULL,
[SecurityName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecurityShortName] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecurityShortNameEnum] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecurityGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecuritySubGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecuritySegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecurityValidCode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecurityCRM] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecurityFixedAsset] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetClass] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecurityType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrencyType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RVPresentCheck] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIBILSecurityCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BaselSecurityCRM] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysSecurityCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysSecurityName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysSecurityCode1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysSecurityName1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestSysSecurityCode] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [datetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [datetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [datetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[IRBCollType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IRBMark] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
