CREATE TABLE [dbo].[ENBD_RESTR_DATA]
(
[RestructureStage] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Source System] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefCustomerId] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefSystemAcId] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RestructureFacilityTypeAlt_Key] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvocationDate] [datetime] NULL,
[RestructureDt] [datetime] NULL,
[PrincRepayStartDate] [datetime] NULL,
[InttRepayStartDate] [datetime] NULL,
[SP_ExpireDate] [datetime] NULL,
[MP_ExpireDate] [datetime] NULL,
[PreRestructureAssetClassAlt_Key] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Current Status] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreRestructureNPA_Date] [datetime] NULL,
[Post restructure slippage date] [datetime] NULL,
[ProvPerOnRestrucure] [float] NULL,
[RestructureTypeAlt_Key] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COVID_OTR_CatgAlt_Key] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlgMorat] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlgInvestmentGrade] [float] NULL,
[RestructreTOS] [float] NULL,
[RestructurePOS] [float] NULL,
[CurrentPOS] [float] NULL,
[DPD_30_90_Breach_Date] [datetime] NULL,
[DefaultDate] [float] NULL,
[ZeroDPD_Date] [datetime] NULL,
[SP_ExtendedDate] [datetime] NULL,
[UpgradeDate] [datetime] NULL,
[SurvilancePeriodDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F30] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
