CREATE TABLE [dbo].[DimCreditRating]
(
[CreditRating_Key] [smallint] NOT NULL,
[CreditRatingAlt_Key] [smallint] NULL,
[CreditRatingOrderKey] [tinyint] NULL,
[CreditRatingName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditRatingShortName] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditRatingShortNameEnum] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditRatingGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditRatingSubGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditRatingSegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditRatingValidCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditScoreLowerValue] [smallint] NULL,
[CreditScoreUpperValue] [smallint] NULL,
[OldCreditRatingShortNameEnum] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysCreditRatingCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysCreditRatingName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestSysCreditRatingCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModifie] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL
) ON [PRIMARY]
GO
