CREATE TABLE [dbo].[InvMOC_ChangeDetails]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[MOCType_Flag] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UCIC_ID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetClassAlt_Key] [int] NULL,
[BookValueINR] [decimal] (18, 2) NULL,
[MTMValue] [decimal] (18, 2) NULL,
[SMA_Dt] [date] NULL,
[SMA_Class] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NPA_Date] [date] NULL,
[AddlProvPer] [decimal] (5, 2) NULL,
[AddlProvAbs] [decimal] (16, 2) NULL,
[SecurityValue] [decimal] (16, 2) NULL,
[FlgRestructure] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RestructureDate] [date] NULL,
[FlgFraud] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FraudDate] [date] NULL,
[MOC_ExpireDate] [date] NULL,
[MOC_Reason] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOC_Date] [date] NULL,
[MOC_By] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOC_Source] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [datetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [datetime] NULL,
[ApprovedByFirstLevel] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApprovedFirstLevel] [datetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [datetime] NULL,
[MOCTYPE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOCProcessed] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
