CREATE TABLE [dbo].[SECURITY_ISSUE]
(
[Report Date] [datetime] NULL,
[UCIC] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIF ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Borrower Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Branch Code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Branch Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account No ] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Source System] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Facility] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scheme Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scheme Code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scheme Description] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Secured Unsecured] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Seg Code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Segment Description] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Segment] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account DPD] [float] NULL,
[Cycle Past due] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NPA Date] [datetime] NULL,
[Asset Classification] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NPA Norms] [float] NULL,
[Balance Outstanding] [float] NULL,
[Customer Security Value] [float] NULL,
[Security Value Appropriated] [float] NULL,
[Secured Outstanding] [float] NULL,
[Unsecured Outstanding] [float] NULL,
[Provision Total] [float] NULL,
[Provision Secured] [float] NULL,
[Provision Unsecured] [float] NULL,
[Net NPA] [float] NULL,
[ProvisionSecured%] [float] NULL,
[ProvisionUnSecured%] [float] NULL,
[ProvisionTotal%] [float] NULL
) ON [PRIMARY]
GO
