CREATE TABLE [dbo].[CustomerLevelMOC_Mod_231221]
(
[Entity_Key] [int] NOT NULL IDENTITY(1, 1),
[CustomerID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerEntityID] [int] NULL,
[AssetClass] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetClassAlt_Key] [int] NULL,
[NPADate] [date] NULL,
[SecurityValue] [decimal] (18, 2) NULL,
[AdditionalProvision] [decimal] (16, 2) NULL,
[FraudAccountFlagAlt_Key] [int] NULL,
[FraudDate] [date] NULL,
[MOCTypeAlt_Key] [int] NULL,
[MOCType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOCReason] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOCDate] [date] NULL,
[MOCBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateOfDate] [date] NULL,
[Level1ApprovedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Level2ApprovedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[AuthorisationStatus] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [datetime] NULL,
[ModifiedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [datetime] NULL,
[ApprovedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [datetime] NULL,
[MOCSourceAltkey] [int] NULL,
[ScreenFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ApprovedByFirstLevel] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApprovedFirstLevel] [datetime] NULL,
[SrNo] [int] NULL,
[UploadID] [int] NULL,
[MOCSource] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifyBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChangeField] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOCType_Flag] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
