CREATE TABLE [dbo].[Accountcal_1012]
(
[EntityKey] [bigint] NOT NULL IDENTITY(1, 1),
[AccountEntityID] [int] NOT NULL,
[UcifEntityID] [int] NULL,
[CustomerEntityID] [int] NULL,
[CustomerAcID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefCustomerID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceSystemCustomerID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UCIF_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FacilityType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AcOpenDt] [date] NULL,
[FirstDtOfDisb] [date] NULL,
[ProductAlt_Key] [int] NULL,
[SchemeAlt_key] [int] NULL,
[SubSectorAlt_Key] [int] NULL,
[SplCatg1Alt_Key] [int] NULL,
[SplCatg2Alt_Key] [int] NULL,
[SplCatg3Alt_Key] [int] NULL,
[SplCatg4Alt_Key] [int] NULL,
[SourceAlt_Key] [tinyint] NULL,
[ActSegmentCode] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InttRate] [decimal] (16, 8) NULL,
[Balance] [decimal] (16, 2) NULL,
[BalanceInCrncy] [decimal] (16, 2) NULL,
[CurrencyAlt_Key] [int] NULL,
[DrawingPower] [decimal] (16, 2) NULL,
[CurrentLimit] [decimal] (16, 2) NULL,
[CurrentLimitDt] [date] NULL,
[ContiExcessDt] [date] NULL,
[StockStDt] [date] NULL,
[DebitSinceDt] [date] NULL,
[LastCrDate] [date] NULL,
[InttServiced] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntNotServicedDt] [date] NULL,
[OverdueAmt] [decimal] (18, 2) NULL,
[OverDueSinceDt] [date] NULL,
[ReviewDueDt] [date] NULL,
[SecurityValue] [decimal] (24, 0) NULL,
[DFVAmt] [decimal] (16, 2) NULL,
[GovtGtyAmt] [decimal] (16, 2) NULL,
[CoverGovGur] [decimal] (16, 2) NULL,
[WriteOffAmount] [decimal] (16, 2) NULL,
[UnAdjSubSidy] [decimal] (16, 2) NULL,
[CreditsinceDt] [date] NULL,
[DegReason] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Asset_Norm] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REFPeriodMax] [int] NULL,
[RefPeriodOverdue] [smallint] NULL,
[RefPeriodOverDrawn] [smallint] NULL,
[RefPeriodNoCredit] [smallint] NULL,
[RefPeriodIntService] [smallint] NULL,
[RefPeriodStkStatement] [smallint] NULL,
[RefPeriodReview] [smallint] NULL,
[NetBalance] [decimal] (16, 2) NULL,
[ApprRV] [decimal] (22, 2) NULL,
[SecuredAmt] [decimal] (16, 2) NULL,
[UnSecuredAmt] [decimal] (16, 2) NULL,
[ProvDFV] [decimal] (16, 2) NULL,
[Provsecured] [decimal] (16, 2) NULL,
[ProvUnsecured] [decimal] (16, 2) NULL,
[ProvCoverGovGur] [decimal] (16, 2) NULL,
[AddlProvision] [decimal] (16, 2) NULL,
[TotalProvision] [decimal] (16, 2) NULL,
[BankProvsecured] [decimal] (16, 2) NULL,
[BankProvUnsecured] [decimal] (16, 2) NULL,
[BankTotalProvision] [decimal] (16, 2) NULL,
[RBIProvsecured] [decimal] (18, 2) NULL,
[RBIProvUnsecured] [decimal] (18, 2) NULL,
[RBITotalProvision] [decimal] (18, 2) NULL,
[InitialNpaDt] [date] NULL,
[FinalNpaDt] [date] NULL,
[SMA_Dt] [date] NULL,
[UpgDate] [date] NULL,
[InitialAssetClassAlt_Key] [int] NULL,
[FinalAssetClassAlt_Key] [int] NULL,
[ProvisionAlt_Key] [int] NULL,
[PNPA_Reason] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMA_Class] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMA_Reason] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlgMoc] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOC_Dt] [date] NULL,
[CommonMocTypeAlt_Key] [smallint] NULL,
[FlgDeg] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlgDirtyRow] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlgInMonth] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlgSMA] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlgPNPA] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlgUpg] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlgFITL] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlgAbinitio] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NPA_Days] [int] NULL,
[RefPeriodOverdueUPG] [smallint] NULL,
[RefPeriodOverDrawnUPG] [smallint] NULL,
[RefPeriodNoCreditUPG] [smallint] NULL,
[RefPeriodIntServiceUPG] [smallint] NULL,
[RefPeriodStkStatementUPG] [smallint] NULL,
[RefPeriodReviewUPG] [smallint] NULL,
[EffectiveFromTimeKey] [int] NOT NULL,
[EffectiveToTimeKey] [int] NOT NULL,
[AppGovGur] [decimal] (18, 2) NULL,
[UsedRV] [decimal] (18, 2) NULL,
[ComputedClaim] [decimal] (22, 2) NULL,
[UPG_RELAX_MSME] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEG_RELAX_MSME] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PNPA_DATE] [date] NULL,
[NPA_Reason] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PnpaAssetClassAlt_key] [int] NULL,
[DisbAmount] [decimal] (18, 2) NULL,
[PrincOutStd] [decimal] (18, 2) NULL,
[PrincOverdue] [decimal] (18, 2) NULL,
[PrincOverdueSinceDt] [date] NULL,
[IntOverdue] [decimal] (18, 2) NULL,
[IntOverdueSinceDt] [date] NULL,
[OtherOverdue] [decimal] (18, 2) NULL,
[OtherOverdueSinceDt] [date] NULL,
[RelationshipNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountFlag] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CommercialFlag_AltKey] [smallint] NULL,
[Liability] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CD] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountStatus] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountBlkCode1] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountBlkCode2] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExposureType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mtm_Value] [decimal] (18, 2) NULL,
[BankAssetClass] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NpaType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecApp] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BorrowerTypeID] [int] NULL,
[LineCode] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProvPerSecured] [decimal] (10, 4) NULL,
[ProvPerUnSecured] [decimal] (10, 4) NULL,
[MOCReason] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddlProvisionPer] [decimal] (6, 2) NULL,
[FlgINFRA] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RepossessionDate] [date] NULL,
[DerecognisedInterest1] [decimal] (14, 0) NULL,
[DerecognisedInterest2] [decimal] (14, 0) NULL,
[ProductCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlgLCBG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[unserviedint] [decimal] (18, 2) NULL,
[PreQtrCredit] [decimal] (18, 2) NULL,
[PrvQtrInt] [decimal] (18, 2) NULL,
[CurQtrCredit] [decimal] (18, 2) NULL,
[CurQtrInt] [decimal] (18, 2) NULL,
[OriginalBranchcode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdvanceRecovery] [decimal] (16, 2) NULL,
[NotionalInttAmt] [decimal] (16, 2) NULL,
[PrvAssetClassAlt_Key] [int] NULL,
[MOCTYPE] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlgSecured] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RePossession] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCPending] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaymentPending] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WheelCase] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerLevelMaxPer] [decimal] (5, 2) NULL,
[FinalProvisionPer] [decimal] (5, 2) NULL,
[IsIBPC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsSecuritised] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RFA] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsNonCooperative] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sarfaesi] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WeakAccount] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PUI] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlgRestructure] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RestructureDate] [date] NULL,
[WeakAccountDate] [date] NULL,
[SarfaesiDate] [date] NULL,
[FlgUnusualBounce] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnusualBounceDate] [date] NULL,
[FlgUnClearedEffect] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnClearedEffectDate] [date] NULL,
[FlgFraud] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FraudDate] [date] NULL,
[ScreenFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChangeField] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
