CREATE TABLE [dbo].[AdvAcFinancialDetail_10012022]
(
[ENTITYKEY] [bigint] NOT NULL,
[AccountEntityId] [int] NOT NULL,
[Ac_LastReviewDueDt] [date] NULL,
[Ac_ReviewTypeAlt_key] [smallint] NULL,
[Ac_ReviewDt] [date] NULL,
[Ac_ReviewAuthAlt_Key] [smallint] NULL,
[Ac_NextReviewDueDt] [date] NULL,
[DrawingPower] [decimal] (16, 2) NULL,
[InttRate] [decimal] (4, 2) NULL,
[NpaDt] [date] NULL,
[BookDebts] [decimal] (14, 0) NULL,
[UnDrawnAmt] [decimal] (14, 0) NULL,
[UnAdjSubSidy] [decimal] (14, 0) NULL,
[LastInttRealiseDt] [date] NULL,
[MocStatus] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOCReason] [smallint] NULL,
[LimitDisbursed] [decimal] (14, 0) NULL,
[RefCustomerId] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefSystemAcId] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NOT NULL,
[EffectiveToTimeKey] [int] NOT NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [datetime] NOT NULL,
[MocDate] [smalldatetime] NULL,
[MocTypeAlt_Key] [int] NULL,
[CropDuration] [smallint] NULL,
[Ac_ReviewAuthLevelAlt_Key] [smallint] NULL,
[AccountBlkCode2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
