CREATE TABLE [dbo].[sysdatamatrix_11072022]
(
[MonthFirstDate] [date] NULL,
[MonthLastDate] [date] NULL,
[TimeKey] [int] NULL,
[MonthName] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Month] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Year] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastFriday] [date] NULL,
[LastReportingFriday] [date] NULL,
[CurrentStatus] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prev_Month_Key] [int] NULL,
[Prev_Qtr_key] [int] NULL,
[Prev_Fiscal_HalfYear_key] [int] NULL,
[Prev_Fiscal_Year_key] [int] NULL,
[DataEffectiveFromDate] [date] NULL,
[DataEffectiveToDate] [date] NULL,
[DataEffectiveFromTimeKey] [int] NULL,
[AssetClassificationDt] [date] NULL,
[Week_Key] [int] NULL,
[Fortnight_Key] [int] NULL,
[Month_Key] [int] NULL,
[Qtr_key] [int] NULL,
[Fiscal_HalfYear_key] [int] NULL,
[Fiscal_Year_key] [int] NULL,
[IsClosingDay] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOC_Initialised] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOC_Frozen] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QTR_Initialised] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QTR_Frozen] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BS_MasterFreeze] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProcessingDone] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExtDate] [date] NULL,
[RBSProcessCompleted] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RBSFreezedDone] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RBSFreezedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RBSFreezedDate] [smalldatetime] NULL,
[MocProcessDate] [date] NULL
) ON [PRIMARY]
GO
