CREATE TABLE [dbo].[DimConstitutionMapping]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[ConstitutionMappingAlt_key] [int] NULL,
[ConstitutionAlt_Key] [smallint] NULL,
[SourceAlt_Key] [int] NULL,
[ConstitutionName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConstitutionShortName] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConstitutionShortNameEnum] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConstitutionGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConstitutionSubGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConstitutionSegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConstitutionValidCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BsrOrganisationCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetClass] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIBILConstitution] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIBILDetectConstitutionCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RelationGroup] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrmSecuIssue] [int] NULL,
[BaselExtRtngAppl] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysConstitutionCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysConstitutionName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestSysConstitutionCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [datetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModifie] [datetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [datetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[Remarks] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Remarks1] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysConstitutionCode1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
