CREATE TABLE [dbo].[AdvAcBalanceDetail_backup]
(
[EntityKey] [bigint] NOT NULL,
[AccountEntityId] [int] NOT NULL,
[AssetClassAlt_Key] [smallint] NULL,
[BalanceInCurrency] [decimal] (16, 2) NULL,
[Balance] [decimal] (16, 2) NULL,
[SignBalance] [decimal] (16, 2) NULL,
[LastCrDt] [date] NULL,
[OverDue] [decimal] (16, 2) NULL,
[TotalProv] [decimal] (16, 2) NULL,
[RefCustomerId] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefSystemAcId] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NOT NULL,
[EffectiveToTimeKey] [int] NOT NULL,
[OverDueSinceDt] [date] NULL,
[MocStatus] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MocDate] [smalldatetime] NULL,
[MocTypeAlt_Key] [int] NULL,
[Old_OverDueSinceDt] [date] NULL,
[Old_OverDue] [decimal] (16, 2) NULL,
[ORG_TotalProv] [decimal] (16, 2) NULL,
[IntReverseAmt] [decimal] (16, 2) NULL,
[UnAppliedIntAmount] [decimal] (18, 2) NULL,
[PS_Balance] [decimal] (16, 2) NULL,
[NPS_Balance] [decimal] (16, 2) NULL,
[DateCreated] [date] NULL,
[ModifiedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [date] NULL,
[ApprovedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [date] NULL,
[CreatedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpgradeDate] [date] NULL,
[OverduePrincipal] [decimal] (18, 2) NULL,
[NotionalInttAmt] [decimal] (16, 2) NULL,
[PrincipalBalance] [decimal] (18, 2) NULL,
[Overdueinterest] [decimal] (16, 2) NULL,
[AdvanceRecovery] [decimal] (16, 2) NULL,
[PS_NPS_FLAG] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DFVAmt] [decimal] (18, 2) NULL,
[InterestReceivable] [decimal] (18, 2) NULL,
[OverduePrincipalDt] [date] NULL,
[OverdueIntDt] [date] NULL,
[OverOtherdue] [decimal] (18, 2) NULL,
[OverdueOtherDt] [date] NULL,
[SourceAssetClass] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceNpaDate] [date] NULL
) ON [PRIMARY]
GO
