CREATE TABLE [dbo].[AdvAcWODetail_Mod]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[BranchCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerEntityId] [int] NULL,
[AccountEntityId] [int] NULL,
[CustomerID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerName] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SystemACID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerACID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WOEntityID] [int] NULL,
[RestructureEntityID] [int] NULL,
[GLAlt_Key] [int] NULL,
[ProductAlt_Key] [smallint] NULL,
[GLProductAlt_Key] [smallint] NULL,
[FacilityType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SectorAlt_Key] [smallint] NULL,
[SubSectorAlt_Key] [smallint] NULL,
[ActivityAlt_Key] [smallint] NULL,
[SchemeAlt_Key] [smallint] NULL,
[AssetClassAlt_Key] [smallint] NULL,
[NPADt] [date] NULL,
[WO_PWO] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WriteOffDt] [date] NULL,
[WriteOffAmt] [decimal] (18, 2) NULL,
[SettlementAmt] [decimal] (18, 0) NULL,
[SettlementDt] [date] NULL,
[RecompenseAmt] [decimal] (18, 0) NULL,
[RecompenseDt] [date] NULL,
[SacrificeAmt] [decimal] (18, 0) NULL,
[IntSacrifice] [decimal] (18, 0) NULL,
[FITLSacrifice] [decimal] (18, 0) NULL,
[OthSacrifice] [decimal] (18, 0) NULL,
[FITLAccountRefNo] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[ChangeFields] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Action] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UploadID] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UploadType] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UploadTypeParameterAlt_Key] [int] NULL
) ON [PRIMARY]
GO
