CREATE TABLE [dbo].[AdvAcPUIDetailSub_mod]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[CustomerID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChangeinProjectScope] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FreshOriginalDCCO] [date] NULL,
[RevisedDCCO] [date] NULL,
[CourtCaseArbitration] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChangeinOwnerShip] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIOReferenceDate] [date] NULL,
[CIODCCO] [date] NULL,
[CostOverRun] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RevisedProjectCost] [decimal] (16, 2) NULL,
[RevisedDebt] [decimal] (16, 2) NULL,
[RevisedDebt_EquityRatio] [decimal] (16, 2) NULL,
[TakeOutFinance] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetClassSellerBookAlt_key] [int] NULL,
[NPADateSellerBook] [date] NULL,
[Restructuring] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[AccountEntityId] [int] NULL,
[AccountID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InitialExtenstion] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExtnReason_BCP] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Npa_date] [date] NULL,
[Npa_Reason] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetClassAlt_Key] [smallint] NULL,
[FirstLevelApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstLevelDateApproved] [smalldatetime] NULL,
[ActualDCCO_Achieved] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActualDCCO_Date] [date] NULL,
[RM_CreditOfficer] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[changeFields] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
