CREATE TABLE [dbo].[AClRep]
(
[Report date] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UCIC] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIF ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Borrower Name] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Branch Code] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Branch Name] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account No.] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Source System] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Facility] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scheme Type] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scheme Code] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scheme Description] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Seg Code] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Segment Description] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Segment] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account DPD] [int] NULL,
[NPA Date] [date] NULL,
[Outstanding] [decimal] (16, 2) NULL,
[Principal Outstanding] [decimal] (16, 2) NULL,
[Drawing Power] [decimal] (16, 2) NULL,
[Sanction Limit] [decimal] (16, 2) NULL,
[OverDrawn Amount] [decimal] (17, 2) NULL,
[DPD_Overdrawn] [int] NULL,
[Limit/DP Overdrawn Date] [date] NULL,
[Limit Expiry Date] [date] NULL,
[DPD_Limit Expiry] [int] NULL,
[Stock Statement valuation date] [date] NULL,
[DPD_Stock Statement expiry] [int] NULL,
[Debit Balance Since Date] [date] NULL,
[Last Credit Date] [date] NULL,
[DPD_No Credit] [int] NULL,
[Current quarter credit] [decimal] (16, 2) NULL,
[Current quarter interest] [decimal] (16, 2) NULL,
[Interest Not Serviced] [decimal] (17, 2) NULL,
[DPD_out of order] [int] NULL,
[CC/OD Interest Service] [date] NULL,
[Overdue Amount] [decimal] (18, 2) NULL,
[Overdue Date] [date] NULL,
[DPD_Overdue] [int] NULL,
[Principal Overdue] [decimal] (18, 2) NULL,
[Principal Overdue Date] [date] NULL,
[DPD_Principal Overdue] [int] NULL,
[Interest Overdue] [decimal] (18, 2) NULL,
[Interest Overdue Date] [date] NULL,
[DPD_Interest Overdue] [int] NULL,
[Other OverDue] [decimal] (18, 2) NULL,
[Other OverDue Date] [date] NULL,
[DPD_Other Overdue] [int] NULL,
[Bill/PC Overdue Amount] [decimal] (18, 2) NULL,
[Overdue Bill/PC ID] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Bill/PC Overdue Date] [date] NULL,
[DPD Bill/PC] [int] NULL,
[Asset Classification] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Degrade Reason] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NPA Norms] [smallint] NULL
) ON [PRIMARY]
GO
