CREATE TABLE [dbo].[AdvAcRestructureDetail_Mod]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[AccountEntityId] [int] NULL,
[RestructureTypeAlt_Key] [smallint] NULL,
[RestructureCatgAlt_Key] [smallint] NULL,
[RestructureProposalDt] [date] NULL,
[RestructureAmt] [decimal] (18, 0) NULL,
[RestructureApprovalDt] [date] NULL,
[RestructureSequenceRefNo] [int] NULL,
[DiminutionAmount] [decimal] (18, 0) NULL,
[RestructureByAlt_Key] [int] NULL,
[RefCustomerId] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefSystemAcId] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[OverDueSinceDt] [date] NULL,
[BankApprovalDt] [date] NULL,
[ForwardDt] [date] NULL,
[Remark] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChangeFields] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreRestrucDefaultDate] [datetime] NULL,
[PreRestrucAssetClass] [int] NULL,
[PostRestrucAssetClass] [int] NULL,
[InvocationDate] [datetime] NULL,
[ConversionDate] [datetime] NULL,
[CRILIC_Fst_DefaultDate] [datetime] NULL,
[FstDefaultReportingBank] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICA_SignDate] [datetime] NULL,
[CreditProvision] [decimal] (16, 2) NULL,
[DFVProvision] [decimal] (16, 2) NULL,
[MTMProvision] [decimal] (16, 2) NULL,
[DisbursementDate] [date] NULL,
[RestructurePOS] [decimal] (16, 2) NULL,
[Restructure_NPA_Dt] [date] NULL,
[RestructureDt] [date] NULL,
[BankingRelationTypeAlt_Key] [int] NULL,
[EquityConversionYN] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrincRepayStartDate] [date] NULL,
[InttRepayStartDate] [datetime] NULL,
[PreRestructureAssetClassAlt_Key] [int] NULL,
[PreRestructureNPA_Date] [datetime] NULL,
[COVID_OTR_CatgAlt_Key] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RestructureApprovingAuthority] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvestmentGrade] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlgMorat] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreRestructureNPA_Prov] [decimal] (16, 2) NULL,
[StatusofSpecificPeriod] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AdvAcRestructureDetail_Mod] ADD CONSTRAINT [PK_AdvAcRestructureDetail1] PRIMARY KEY NONCLUSTERED ([EntityKey]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
