CREATE TABLE [dbo].[MOC_PROV_REPORT_DATA]
(
[Report Date] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UCIC] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIF ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Borrower Name] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Branch Code] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Branch Name] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account No.] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Source System] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Facility] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scheme Type] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scheme Code] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scheme Description] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Secured/Unsecured] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Seg Code] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Segment Description] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Segment] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account DPD] [int] NULL,
[Cycle Past due] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NPA Date] [date] NULL,
[Asset Classification] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NPA Norms] [smallint] NULL,
[Balance Outstanding] [decimal] (16, 2) NULL,
[Customer Security Value] [decimal] (18, 2) NULL,
[Security Value Appropriated] [decimal] (22, 2) NULL,
[Secured Outstanding] [decimal] (16, 2) NULL,
[Unsecured Outstanding] [decimal] (16, 2) NULL,
[Provision Total] [decimal] (16, 2) NULL,
[Provision Secured] [decimal] (16, 2) NULL,
[Provision Unsecured] [decimal] (16, 2) NULL,
[Net NPA] [decimal] (17, 2) NOT NULL,
[ProvisionSecured%] [decimal] (5, 2) NULL,
[ProvisionUnSecured%] [decimal] (5, 2) NULL,
[ProvisionTotal%] [decimal] (5, 2) NULL,
[Prev. Qtr. Balance Outstanding] [decimal] (16, 2) NOT NULL,
[Prev. Qtr. Secured Outstanding] [decimal] (16, 2) NOT NULL,
[Prev. Qtr. Unsecured Outstanding] [decimal] (16, 2) NOT NULL,
[Prev. Qtr.Provision Total] [decimal] (16, 2) NOT NULL,
[Prev. Qtr.Provision Secured] [decimal] (16, 2) NOT NULL,
[Prev. Qtr. Provision Unsecured] [decimal] (16, 2) NOT NULL,
[Prev. Qtr. Net NPA] [decimal] (17, 2) NOT NULL,
[NPAIncrease] [decimal] (17, 2) NOT NULL,
[NPADecrease] [decimal] (17, 2) NOT NULL,
[ProvisionIncrease] [decimal] (17, 2) NOT NULL,
[ProvisionDecrease] [decimal] (17, 2) NOT NULL,
[NetNPAIncrease] [decimal] (18, 2) NOT NULL,
[NetNPAnDecrease] [decimal] (18, 2) NOT NULL
) ON [PRIMARY]
GO
