CREATE TABLE [dbo].[Moc_vrification_16012022]
(
[Moc_Status] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CurrentProcessingDate] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrNo] [bigint] NULL,
[SourceName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerAcID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerName] [varchar] (225) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UCIF_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FacilityType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PANNo] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AadharCardNo] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InitialNpaDt] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InitialAssetClassAlt_Key] [int] NULL,
[InitalAssetClassName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstDtOfDisb] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductAlt_Key] [int] NULL,
[ProductName] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Balance] [decimal] (16, 2) NOT NULL,
[PrincOutStd] [decimal] (18, 2) NOT NULL,
[PrincOverdue] [decimal] (18, 2) NOT NULL,
[IntOverdue] [decimal] (18, 2) NOT NULL,
[DrawingPower] [decimal] (16, 2) NOT NULL,
[CurrentLimit] [decimal] (16, 2) NOT NULL,
[ContiExcessDt] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StockStDt] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DebitSinceDt] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastCrDate] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurQtrCredit] [decimal] (18, 2) NOT NULL,
[CurQtrInt] [decimal] (18, 2) NOT NULL,
[InttServiced] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntNotServicedDt] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverDueSinceDt] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReviewDueDt] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecurityValue] [decimal] (18, 2) NOT NULL,
[DFVAmt] [decimal] (16, 2) NOT NULL,
[GovtGtyAmt] [decimal] (16, 2) NOT NULL,
[WriteOffAmount] [decimal] (16, 2) NOT NULL,
[UnAdjSubSidy] [decimal] (16, 2) NOT NULL,
[Asset_Norm] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddlProvision] [decimal] (16, 2) NOT NULL,
[PrincOverDueSinceDt] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntOverDueSinceDt] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherOverDueSinceDt] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnserviedInt] [decimal] (18, 2) NOT NULL,
[AdvanceRecovery] [decimal] (16, 2) NOT NULL,
[RePossession] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RepossessionDate] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCPending] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaymentPending] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WheelCase] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RFA] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsNonCooperative] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sarfaesi] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SarfaesiDate] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InherentWeakness] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InherentWeaknessDate] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlgFITL] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlgRestructure] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RestructureDate] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlgUnusualBounce] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnusualBounceDate] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlgUnClearedEffect] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnClearedEffectDate] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoverGovGur] [decimal] (16, 2) NOT NULL,
[DegReason] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NetBalance] [decimal] (16, 2) NOT NULL,
[ApprRV] [decimal] (22, 2) NOT NULL,
[SecuredAmt] [decimal] (16, 2) NOT NULL,
[UnSecuredAmt] [decimal] (16, 2) NOT NULL,
[ProvDFV] [decimal] (16, 2) NOT NULL,
[Provsecured] [decimal] (16, 2) NOT NULL,
[ProvUnsecured] [decimal] (16, 2) NOT NULL,
[ProvCoverGovGur] [decimal] (16, 2) NOT NULL,
[TotalProvision] [decimal] (16, 2) NOT NULL,
[BankTotalProvision] [decimal] (16, 2) NOT NULL,
[RBITotalProvision] [decimal] (18, 2) NOT NULL,
[FinalNpaDt] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoubtfulDt] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpgDate] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FinalAssetClassAlt_Key] [int] NULL,
[FinalAssetClassName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NPA_Reason] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlgDeg] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlgUpg] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FinalProvisiONPer] [decimal] (5, 2) NULL,
[FlgSMA] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMA_Dt] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMA_Class] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMA_Reason] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlgPNPA] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PNPA_DATE] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PNPA_Reason] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustSMAStatus] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOC_Dt] [date] NULL,
[FlgFraud] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FraudDate] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MakerID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MakerDate] [datetime] NULL,
[CheckerID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CheckerDate] [date] NULL,
[ReviewerID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReviewerDate] [date] NULL,
[MOCReason] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AcBuSegmentCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AcBuSegmentDescription] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
