CREATE TABLE [dbo].[advsecuritydetail_12022022]
(
[ENTITYKEY] [bigint] NULL,
[AccountEntityId] [int] NULL,
[CustomerEntityId] [int] NULL,
[SecurityType] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollateralType] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecurityAlt_Key] [smallint] NULL,
[SecurityEntityID] [int] NOT NULL,
[Security_RefNo] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecurityNature] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecurityChargeTypeAlt_Key] [int] NULL,
[CurrencyAlt_Key] [smallint] NULL,
[EntryType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ScrCrError] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InwardNo] [smallint] NULL,
[Limitnode_Flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefSystemAcId] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NOT NULL,
[EffectiveToTimeKey] [int] NOT NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [datetime] NULL,
[MocTypeAlt_Key] [int] NULL,
[MocStatus] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MocDate] [smalldatetime] NULL,
[SecurityParticular] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerTypeAlt_Key] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetOwnerName] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAtSanctionTime] [decimal] (16, 2) NULL,
[BranchLastInspecDate] [date] NULL,
[SatisfactionNo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SatisfactionDate] [date] NULL,
[BankShare] [decimal] (5, 2) NULL,
[ActionTakenRemark] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecCharge] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollateralID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UCICID] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerName] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaggingAlt_Key] [int] NULL,
[DistributionAlt_Key] [int] NULL,
[CollateralCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollateralSubTypeAlt_Key] [int] NULL,
[CollateralOwnerShipTypeAlt_Key] [int] NULL,
[ChargeNatureAlt_Key] [int] NULL,
[ShareAvailabletoBankAlt_Key] [int] NULL,
[CollateralShareamount] [decimal] (18, 2) NULL,
[IfPercentagevalue_or_Absolutevalue] [decimal] (16, 2) NULL,
[CollateralValueatSanctioninRs] [decimal] (18, 2) NULL,
[CollateralValueasonNPAdateinRs] [decimal] (18, 2) NULL,
[ApprovedByFirstLevel] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApprovedFirstLevel] [smalldatetime] NULL,
[ChangeField] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChargeType] [int] NULL,
[ChargeNature] [int] NULL,
[RefCustomerId] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
