CREATE TABLE [dbo].[AdvFacCCDetail_mod]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[AccountEntityId] [int] NOT NULL,
[AdhocDt] [date] NULL,
[AdhocAmt] [decimal] (16, 2) NULL,
[ContExcsSinceDt] [date] NULL,
[DerecognisedInterest1] [decimal] (16, 2) NULL,
[DerecognisedInterest2] [decimal] (16, 2) NULL,
[ClaimType] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimCoverAmt] [decimal] (16, 2) NULL,
[ClaimLodgedDt] [date] NULL,
[ClaimLodgedAmt] [decimal] (16, 2) NULL,
[ClaimRecvDt] [date] NULL,
[ClaimReceivedAmt] [decimal] (16, 2) NULL,
[ClaimRate] [decimal] (16, 2) NULL,
[RefSystemAcid] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[MocStatus] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MocDate] [smalldatetime] NULL,
[MocTypeAlt_Key] [int] NULL,
[AdhocExpiryDate] [date] NULL,
[DebitSinceDt] [date] NULL,
[Acc_StkSmtFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChangeFields] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StockStmtDt] [date] NULL
) ON [PRIMARY]
GO
