CREATE TABLE [dbo].[INVESTMENT_DATA]
(
[Process_Date] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BRANCHCODE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISSUERID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISSUERNAME] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REF_TXN_SYS_CUST_ID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISSUER_CATEGORY_CODE] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UCIFID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PANNO] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INVID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISIN] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INSTRUMENTTYPENAME] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INSTRNAME] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INVESTMENTNATURE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPOSURETYPE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MATURITYDT] [date] NULL,
[HOLDINGNATURE] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BOOKTYPE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BOOKVALUE] [decimal] (18, 2) NULL,
[MTMVALUE] [decimal] (18, 2) NULL,
[INTEREST_DIVIDENDDUEDATE] [date] NULL,
[INTEREST_DIVIDENDDUEAMOUNT] [decimal] (16, 2) NULL,
[DPD] [int] NULL,
[FLGDEG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEGREASON] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FLGUPG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UPGDATE] [date] NULL,
[TOTALPROVISON] [decimal] (18, 2) NULL,
[ASSETCLASS] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PartialRedumptionDueDate] [date] NULL,
[PartialRedumptionSettledY_N] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
