CREATE TABLE [dbo].[RP_Portfolio_Upload_Mod]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[CustomerEntityID] [int] NULL,
[UCIC_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAN_No] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BorrowerDefaultDate] [datetime] NULL,
[LeadBankName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefaultStatus] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ImplementationStatus] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Impl_Date] [datetime] NULL,
[RP_OutOfDateAllBanksDeadline] [datetime] NULL,
[ChangeFields] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Remarks] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[AuthorisationStatus] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[ReportingBank_LenderCode] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankArrangementDesc] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExposureBucket] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefrenceDate] [date] NULL,
[ICAStatus] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NotSigingICAReason] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICAExecutionDate] [date] NULL,
[NatureRPApprovalDate] [date] NULL,
[RPNature] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherRPNature] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IBCFilingDate] [date] NULL,
[IBCAddmissionDate] [date] NULL,
[StatusOfRevisedRPDeadline] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrNo] [int] NULL,
[UploadID] [int] NULL,
[ApprovedByFirstLevel] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApprovedFirstLevel] [datetime] NULL,
[BorrowerPAN] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChangeField] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IfRPisRectificationthenRiskReviewTimeline] [datetime] NULL
) ON [PRIMARY]
GO
