CREATE TABLE [dbo].[CollateralMgmt]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[CollateralAlt_Key] [int] NULL,
[AccountID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UCICID] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerName] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaggingAlt_Key] [int] NULL,
[DistributionAlt_Key] [int] NULL,
[CollateralID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollateralCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollateralTypeAlt_Key] [int] NULL,
[CollateralSubTypeAlt_Key] [int] NULL,
[CollateralOwnerTypeAlt_Key] [int] NULL,
[CollateralOwnerShipTypeAlt_Key] [int] NULL,
[ChargeTypeAlt_Key] [int] NULL,
[ChargeNatureAlt_Key] [int] NULL,
[ShareAvailabletoBankAlt_Key] [int] NULL,
[CollateralShareamount] [decimal] (18, 2) NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[AuthorisationStatus] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [datetime] NULL,
[ModifiedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [datetime] NULL,
[ApprovedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [datetime] NULL,
[TotalCollateralvalueatcustomerlevel] [decimal] (18, 2) NULL,
[OldCollateralID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotCollateralsUCICCustAcc] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IfPercentagevalue_or_Absolutevalue] [decimal] (16, 2) NULL
) ON [PRIMARY]
GO
