CREATE TABLE [dbo].[CollateralDetailUpload_Mod_Backup_15012022]
(
[SrNo] [int] NULL,
[LiabID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UCIC] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustName] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Segment] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRE] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollateralSubType] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameSecuPv] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeniorityCharge] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecurityStatus] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FDNO] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISINNo_FolioNumber] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QtyShares_MutualFunds_Bonds] [bigint] NULL,
[Line_No] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrossCollateral_LiabID] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PropertyAdd] [varchar] (2500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PIN] [int] NULL,
[DtStockAudit] [date] NULL,
[SBLCIssuingBank] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SBLCNumber] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurSBLCissued] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SBLCFCY] [decimal] (16, 2) NULL,
[DtexpirySBLC] [date] NULL,
[DtexpiryLIC] [date] NULL,
[ModeOperation] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExceApproval] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValSource_ExpBusinessRule] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DtofValuation] [date] NULL,
[ValueConsidered] [decimal] (16, 2) NULL,
[SecondDtofValuation] [date] NULL,
[SecondValuation] [decimal] (16, 2) NULL,
[UploadID] [int] NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[AuthorisationStatus] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Changes] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Remark] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [datetime] NULL,
[ModifiedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [datetime] NULL,
[ApprovedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [datetime] NULL,
[CollateralID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Expirydate] [date] NULL,
[Action] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollateralIDModification] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
