CREATE TABLE [dbo].[BuyoutFinalDetails]
(
[Entity_Key] [int] NOT NULL IDENTITY(1, 1),
[SummaryID] [int] NULL,
[SlNo] [int] NULL,
[CIFId] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ENBDAcNo] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BuyoutPartyLoanNo] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PartnerDPD] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PartnerDPDAsOnDate] [datetime] NULL,
[PartnerAssetClass] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PartnerNPADate] [datetime] NULL,
[AuthorisationStatus] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Changes] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Remark] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [date] NULL,
[ModifyBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [date] NULL,
[ApprovedBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [date] NULL,
[SecurityValue] [decimal] (18, 2) NULL,
[FinalNpaDt] [date] NULL,
[FinalAssetClassAlt_Key] [smallint] NULL,
[ProvisionAlt_Key] [smallint] NULL,
[NetBalance] [decimal] (18, 2) NULL,
[ApprRV] [decimal] (18, 2) NULL,
[SecuredAmt] [decimal] (18, 2) NULL,
[UnSecuredAmt] [decimal] (18, 2) NULL,
[UsedRV] [decimal] (18, 2) NULL,
[Provsecured] [decimal] (18, 2) NULL,
[ProvUnsecured] [decimal] (18, 2) NULL,
[TotalProvision] [decimal] (18, 2) NULL,
[FLGDEG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FLGUPG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DegReason] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpgDate] [date] NULL,
[PrevProvPercentage] [decimal] (16, 2) NULL,
[FinalProvPercentage] [decimal] (16, 2) NULL,
[Action] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddlProvision] [decimal] (16, 2) NULL
) ON [PRIMARY]
GO
