CREATE TABLE [dbo].[InvestmentFinancialDetail_mod]
(
[EntityKey] [bigint] NOT NULL IDENTITY(1, 1),
[InvEntityId] [int] NOT NULL,
[RefInvID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefIssuerID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HoldingNature] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrencyAlt_Key] [tinyint] NULL,
[CurrencyConvRate] [decimal] (12, 4) NULL,
[BookType] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BookValue] [decimal] (18, 2) NULL,
[BookValueINR] [decimal] (18, 2) NULL,
[MTMValue] [decimal] (18, 2) NULL,
[MTMValueINR] [decimal] (18, 2) NULL,
[EncumberedMTM] [decimal] (18, 2) NULL,
[AssetClass_AltKey] [tinyint] NULL,
[NPIDt] [date] NULL,
[TotalProvison] [decimal] (18, 2) NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NOT NULL,
[EffectiveToTimeKey] [int] NOT NULL,
[CreatedBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[DBTDate] [date] NULL,
[LatestBSDate] [date] NULL,
[Interest_DividendDueDate] [date] NULL,
[Interest_DividendDueAmount] [decimal] (16, 2) NULL,
[PartialRedumptionDueDate] [date] NULL,
[PartialRedumptionSettledY_N] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[changefields] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FLGDEG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEGREASON] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DPD] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FLGUPG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpgDate] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
