CREATE TABLE [dbo].[MetaTextReportColHead]
(
[Column_Key] [smallint] NULL,
[ColumnAlt_Key] [smallint] NULL,
[ColoumnOrder_Key] [smallint] NULL,
[ColoumnRowIndex] [smallint] NULL,
[ColumnName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ColumnHeader] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ColumnSep] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ColumnGroupSep] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RowSep] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RowGroupSep] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UseColumnWidth] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ColumnWidth] [smallint] NULL,
[DataType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DataFormat] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ColumnAlign] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RowSum] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllowSpace] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UseAllowSpaceForTtl] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ColSum] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SplitReq] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportMenuId] [smallint] NULL,
[ColumnValidCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModifie] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL
) ON [PRIMARY]
GO
