CREATE TABLE [dbo].[DimRegion]
(
[Region_Key] [smallint] NOT NULL,
[RegionAlt_Key] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RegionName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RegionShortName] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RegionShortNameEnum] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RegionGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RegionSubGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RegionSegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RegionValidCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZoneAlt_Key] [smallint] NOT NULL,
[ZoneName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RBI_Part_1] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RBI_Part_2] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysRegionCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysRegionName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestSysRegionCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RegionNameHindi] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[BranchLoop] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[regional_Head_EmailId] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeputyRegional_Head_EmailId] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactPersonId] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChangeFields] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RegionCode] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
