CREATE TABLE [dbo].[DimBranch_Mod]
(
[BranchAlt_Key] [int] NOT NULL,
[Branch_Key] [smallint] NOT NULL IDENTITY(1, 1),
[BankCode] [int] NULL,
[BranchCode] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchCode2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Add_1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Add_2] [varchar] (55) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Place] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PinCode] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CityAlt_Key] [smallint] NULL,
[RBI_LicenceNo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RBI_LicenceDt] [date] NULL,
[AuthorisationNo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationDt] [date] NULL,
[TAN] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RBI_TierClass] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RBI_Part_1] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RBI_Part_2] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchOpenDt] [date] NULL,
[BranchShortName] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchShortNameEnum] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchSubGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchSegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchValidCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchRegionAlt_Key] [smallint] NULL,
[BranchRegion] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchZoneAlt_Key] [smallint] NULL,
[BranchZone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchAreaCategoryAlt_Key] [smallint] NULL,
[BranchAreaCategory] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchBusinessCategory] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchScale] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchDistrictAlt_Key] [smallint] NULL,
[BranchDistrictName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchStateAlt_Key] [smallint] NULL,
[BranchStateName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchTerritoryAlt_Key] [smallint] NULL,
[BranchTerritoryName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CibilBrCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InspCentreAlt_Key] [smallint] NULL,
[BranchBlockAlt_Key] [smallint] NULL,
[BranchBlockName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CashRetentionLimit] [decimal] (16, 2) NULL,
[ADCode] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BaseBranchCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OpenTime] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CloseTime] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NonWorkingDay] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NonBankingDay] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SatOpenTime] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SatCloseTime] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchUpgradedYN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpgradationDt] [date] NULL,
[BranchShiftedYN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShiftingDt] [date] NULL,
[ReasonsForShifting] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewAddressUnderSameCenterYN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchMergedYN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MergingDt] [date] NULL,
[MergedwithBranchCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PremisesVacatedOn] [date] NULL,
[RefBranch_Key] [smallint] NULL,
[ExtentionCounterYN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchRegionHindi] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchNameHindi] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OfficialLanguageCatg] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchCloseDt] [date] NULL,
[BrAcNo] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllowPreDisb] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllowLogin] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Acct_Upload] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllowMakerChecker] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrentAllowPreDisb] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysBranchCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysBranchName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestSysBranchCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[Add_3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubscriptionFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contactpersonid] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CountryAlt_Key] [int] NULL,
[changefields] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ApprovedByFirstLevel] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApprovedFirstLevel] [datetime] NULL
) ON [PRIMARY]
GO
