CREATE TABLE [dbo].[temp31]
(
[RowNumber] [bigint] NULL,
[TotalCount] [int] NULL,
[TableName] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UCIC_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankingArrangementAlt_Key] [smallint] NULL,
[BorrowerDefaultDate] [datetime] NULL,
[BorroweDefaultStatus] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LeadBankAlt_Key] [smallint] NULL,
[DefaultStatusAlt_Key] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExposureBucketAlt_Key] [smallint] NULL,
[ReferenceDate] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReviewExpiryDate] [datetime] NULL,
[RP_ApprovalDate] [datetime] NULL,
[RPNatureAlt_Key] [smallint] NULL,
[If_Other] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RP_ExpiryDate] [datetime] NULL,
[RP_ImplDate] [datetime] NULL,
[RP_ImplStatusAlt_Key] [smallint] NULL,
[RP_failed] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Revised_RP_Expiry_Date] [datetime] NULL,
[RevisedRPDeadline_Altkey] [int] NULL,
[Actual_Impl_Date] [datetime] NULL,
[RP_OutOfDateAllBanksDeadline] [datetime] NULL,
[RBLExposure] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetClassAlt_Key] [smallint] NULL,
[RiskReviewExpiryDate] [datetime] NULL,
[NameOf1stReportingBanklenderAlt_Key2] [smallint] NULL,
[NameOf1stReportingBanklenderAlt_Key] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICAStatusAlt_Key] [smallint] NULL,
[ReasonnotsigningICA] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICAExecutionDate] [date] NULL,
[IBCFillingDate] [date] NULL,
[IBCAddmissionDate] [date] NULL,
[IsActive] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InDefaultDate] [datetime] NULL,
[AuthorisationStatus] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ApprovedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[ModifiedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[CrModBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrModDate] [smalldatetime] NULL,
[CrAppBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrAppDate] [smalldatetime] NULL,
[ModAppBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModAppDate] [smalldatetime] NULL,
[ChangeField] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
