CREATE TABLE [dbo].[DynamicReportDirectory]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[ExcelId] [int] NULL,
[ExcelSheetName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportId] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportName] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportType] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FrequencyAlt_Key] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportAmountIn] [decimal] (14, 2) NULL,
[ExcelRowStartPosition] [int] NULL,
[ExcelColumnStartPosition] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SqlSelect] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SqlFrom] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SqlWhere] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SqlGroupBy] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SqlOrderBy] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OutputRowBreak] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsOutputRowBreakRepeat] [bit] NULL,
[IsOutputRowBreakTotal] [bit] NULL,
[IsRowTotal] [bit] NULL,
[IsColumnTotal] [bit] NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifyBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[IsCombined] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumberUnit] [int] NULL,
[tagAltkeys] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BaseConditionItems] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsFreezed] [bit] NULL,
[FreezedBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateFreezed] [datetime] NULL,
[ApplySerialNo] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scope] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportBaseItem] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllowMOC] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportTypeRDL] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportRdlFullName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportUrl] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportMenuId] [int] NULL,
[ReportFrequency_Key] [int] NULL,
[ReportRdlName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VersionNo] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExportReportName] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExportReportId] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Frequency_Period] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateAlt_Key] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportSequence] [int] NULL,
[ReadUptoForCSV] [int] NULL,
[Block_StatePositionName] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fromDateRowPosition] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToDateRowPosition] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fromDateColPosition] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToDateColPosition] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankCodeRowPosition] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankNameRowPosition] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankCodeColPosition] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankNameColPosition] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportDay] [int] NULL,
[ReportSource] [int] NULL,
[Uploads] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GroupApplicableYN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
