CREATE TABLE [dbo].[DimProduct]
(
[ProductAlt_Key] [smallint] NOT NULL,
[ProductCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductName] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductShortName] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductShortNameEnum] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductSubGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductSegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductValidCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysProductCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysProductName] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestSysProductCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModifie] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[DepositType] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceAlt_Key] [int] NULL,
[Product_Key] [int] NOT NULL IDENTITY(1, 1),
[EffectiveFromDate] [int] NULL,
[FacilityType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NPANorms] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SchemeType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Agrischeme] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReviewFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetClass] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConvFactor] [smallint] NULL,
[DefaultType] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefaultLogic] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Segment] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
