CREATE TABLE [dbo].[AdvCustCommunicationDetail_Mod]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[CustomerEntityId] [int] NULL,
[RelationEntityId] [int] NULL,
[RelationAddEntityId] [int] NULL,
[AddressCategoryAlt_Key] [int] NULL,
[AddressTypeAlt_Key] [int] NULL,
[Add1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Add2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Add3] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CountryAlt_Key] [smallint] NULL,
[DistrictAlt_Key] [smallint] NULL,
[CityAlt_Key] [smallint] NULL,
[PinCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustLocationCode] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STD_Code_Res] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhoneNo_Res] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STD_Code_Off] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhoneNo_Off] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FaxNo] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExtensionNo] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ScrCrError] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefCustomerId] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsMainAddress] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[DUNSNo] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIBILPGId] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CityName] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ScrCrErrorSeq] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChangeFields] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
