CREATE TABLE [dbo].[RP_Portfolio_Details_Mod_26042022]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[PAN_No] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UCIC_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankingArrangementAlt_Key] [smallint] NULL,
[BorrowerDefaultDate] [datetime] NULL,
[LeadBankAlt_Key] [smallint] NULL,
[DefaultStatusAlt_Key] [smallint] NULL,
[ExposureBucketAlt_Key] [smallint] NULL,
[ReferenceDate] [datetime] NULL,
[ReviewExpiryDate] [datetime] NULL,
[RP_ApprovalDate] [datetime] NULL,
[RPNatureAlt_Key] [smallint] NULL,
[If_Other] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RP_ExpiryDate] [datetime] NULL,
[RP_ImplDate] [datetime] NULL,
[RP_ImplStatusAlt_Key] [smallint] NULL,
[RP_failed] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Revised_RP_Expiry_Date] [datetime] NULL,
[Actual_Impl_Date] [datetime] NULL,
[RP_OutOfDateAllBanksDeadline] [datetime] NULL,
[IsBankExposure] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetClassAlt_Key] [smallint] NULL,
[RiskReviewExpiryDate] [datetime] NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[ChangeFields] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Remarks] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL
) ON [PRIMARY]
GO
