CREATE TABLE [dbo].[DimGeography]
(
[District_Key] [smallint] NOT NULL,
[DistrictAlt_Key] [smallint] NOT NULL,
[DistrictName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[StateAlt_Key] [smallint] NOT NULL,
[StateName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TerritoryAlt_Key] [smallint] NULL,
[TerritoryName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GeographyShortName] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GeographyShortNameEnum] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GeographyGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GeographySubGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GeographySegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GeographyValidCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IdentifiedDist] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MajorityReligionAlt_Key] [smallint] NULL,
[SrcSysDistrictCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysDistrictName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestSysDistrictCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestSysStateCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnderBanked] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifyBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL
) ON [PRIMARY]
GO
