CREATE TABLE [dbo].[Fraud_Details_21072022]
(
[EntityKey] [bigint] NOT NULL IDENTITY(1, 1),
[AccountEntityId] [int] NULL,
[CustomerEntityId] [int] NULL,
[RefCustomerACID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefCustomerID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RFA_ReportingByBank] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RFA_DateReportingByBank] [date] NULL,
[RFA_OtherBankAltKey] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RFA_OtherBankDate] [date] NULL,
[FraudOccuranceDate] [date] NULL,
[FraudDeclarationDate] [date] NULL,
[FraudNature] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FraudArea] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrentAssetClassAltKey] [int] NULL,
[ProvPref] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NOT NULL,
[EffectiveToTimeKey] [int] NOT NULL,
[CreatedBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[FirstLevelApprovedBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstLevelDateApproved] [date] NULL,
[screenFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UploadID] [int] NULL,
[SrNo] [int] NULL,
[NPA_DateAtFraud] [date] NULL,
[AssetClassAtFraudAltKey] [int] NULL,
[Action] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReasonforRFAClassification] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateofRemovalofRFAClassification] [date] NULL,
[ReasonforRemovalofRFAClassification] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateofRemovalofRFAClassificationReporting] [date] NULL,
[RFAReportedOtherBank] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameofBank] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetClassAlt_KeyBeforeFruad] [int] NULL,
[NPADateBeforeFraud] [date] NULL
) ON [PRIMARY]
GO
