CREATE TABLE [dbo].[ADVACRESTRUCTUREDETAIL_13012022]
(
[EntityKey] [bigint] NOT NULL IDENTITY(1, 1),
[AccountEntityId] [int] NULL,
[RestructureTypeAlt_Key] [smallint] NULL,
[RestructureProposalDt] [date] NULL,
[RestructureDt] [date] NULL,
[RestructureAmt] [decimal] (18, 0) NULL,
[RestructureApprovalDt] [date] NULL,
[RestructureSequenceRefNo] [int] NULL,
[DiminutionAmount] [decimal] (18, 0) NULL,
[RestructureByAlt_Key] [int] NULL,
[RefCustomerId] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefSystemAcId] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SDR_INVOKED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SDR_REFER_DATE] [date] NULL,
[Remark] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RestructureFacilityTypeAlt_Key] [smallint] NULL,
[BankingRelationTypeAlt_Key] [smallint] NULL,
[InvocationDate] [date] NULL,
[AssetClassAlt_KeyOnInvocation] [smallint] NULL,
[EquityConversionYN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConversionDate] [date] NULL,
[PrincRepayStartDate] [date] NULL,
[InttRepayStartDate] [date] NULL,
[PreRestructureAssetClassAlt_Key] [smallint] NULL,
[PreRestructureNPA_Date] [date] NULL,
[ProvPerOnRestrucure] [decimal] (5, 2) NULL,
[COVID_OTR_CatgAlt_Key] [smallint] NULL,
[RestructureApprovingAuthority] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RestructreTOS] [decimal] (20, 2) NULL,
[UnserviceInttAsOnRestructure] [decimal] (20, 2) NULL,
[RestructurePOS] [decimal] (20, 2) NULL,
[RestructureStage] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RestructureStatus] [smallint] NULL,
[DPD_AsOnRestructure] [smallint] NULL,
[DPD_Breach_Date] [date] NULL,
[ZeroDPD_Date] [date] NULL,
[SurvPeriodEndDate] [date] NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[RestructureFailureDate] [date] NULL,
[UpgradeDate] [date] NULL,
[PreDegProvPer] [decimal] (5, 2) NULL,
[SP_ExpiryExtendedDate] [date] NULL,
[ChangeField] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RestructureDescription] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvestmentGrade] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POS_10PerPaidDate] [date] NULL,
[FlgMorat] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreRestructureNPA_Prov] [decimal] (5, 2) NULL
) ON [PRIMARY]
GO
