CREATE TABLE [dbo].[MetaDynamicScreenField_10052022]
(
[EntityKey] [smallint] NOT NULL IDENTITY(1, 1),
[MenuID] [smallint] NULL,
[ControlID] [int] NULL,
[ParentcontrolID] [int] NULL,
[DisplayRowOrder] [smallint] NULL,
[DisplayColumnOrder] [smallint] NULL,
[ControlName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Label] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ControlType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BaseColumnType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DataType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AutoCmpltMinLength] [tinyint] NULL,
[DataMinLength] [smallint] NULL,
[DataMaxLength] [smallint] NULL,
[Placeholder] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Col_lg] [tinyint] NULL,
[Col_md] [tinyint] NULL,
[Col_sm] [tinyint] NULL,
[SourceTable] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceColumn] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsDBPull] [bit] NULL,
[ReferenceTableFilter] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferenceTable] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferenceColumn] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefColumnValue] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferenceTableCond] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsMandatory] [bit] NULL,
[IsVisible] [bit] NULL,
[IsEditable] [bit] NULL,
[IsUpper] [bit] NULL,
[IsLower] [bit] NULL,
[ValidCode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DisAllowedChar] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllowedChar] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnBlur] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnBlurParameter] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnClick] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnClickParameter] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnChange] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnChangeParameter] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnKeyPress] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnKeyPressParameter] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnFormLoad] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnFormLoadParameter] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefaultValue] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SkipColumnInQuery] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SearchColumn] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsF2Button] [bit] NULL,
[IsCloseButton] [bit] NULL,
[Class] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Style] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsParentToChild] [bit] NULL,
[IsChildToParent] [bit] NULL,
[ApplicableForWorkFlow] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EditprevStageData] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsAlwaysDisable] [bit] NULL,
[ScreenFieldNo] [int] NULL,
[IsQuickSearch] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EditLimitDays] [tinyint] NULL,
[IsMocVisible] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
