CREATE TABLE [dbo].[DimSubSector]
(
[SubSector_Key] [smallint] NOT NULL,
[SubSectorAlt_Key] [smallint] NOT NULL,
[SubSectorNameOrderKey] [tinyint] NULL,
[SubSectorName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubSectorShortName] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubSectorShortNameEnum] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubSectorGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubSectorSubGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubSectorSegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubSectorValidCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIBILBusinessCategory] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysSubSectorCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcSysSubSectorName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestSysSubSectorCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestSysSectorCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModifie] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[Remarks] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
