CREATE TABLE [dbo].[AdvAcRestructureDetail_Mod_Backup]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[AccountEntityId] [int] NULL,
[RestructureTypeAlt_Key] [smallint] NULL,
[RestructureCatgAlt_Key] [smallint] NULL,
[RestructureProposalDt] [date] NULL,
[RestructureDt] [date] NULL,
[RestructureAmt] [decimal] (18, 0) NULL,
[ApprovingAuthAlt_Key] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RestructureApprovalDt] [date] NULL,
[RestructureSequenceRefNo] [int] NULL,
[DiminutionAmount] [decimal] (18, 0) NULL,
[RestructureByAlt_Key] [int] NULL,
[RefCustomerId] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefSystemAcId] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[OverDueSinceDt] [date] NULL,
[BankApprovalDt] [date] NULL,
[ForwardDt] [date] NULL,
[Remark] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChangeFields] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreRestrucDefaultDate] [datetime] NULL,
[PreRestrucAssetClass] [int] NULL,
[PreRestrucNPA_Date] [datetime] NULL,
[PostRestrucAssetClass] [int] NULL,
[IntRepayStartDate] [datetime] NULL,
[RefDate] [datetime] NULL,
[InvocationDate] [datetime] NULL,
[IsEquityCoversion] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConversionDate] [datetime] NULL,
[Is_COVID_Morat] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COVID_OTR_Catg] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRILIC_Fst_DefaultDate] [datetime] NULL,
[FstDefaultReportingBank] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICA_SignDate] [datetime] NULL,
[Is_InvestmentGrade] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditProvision] [decimal] (16, 2) NULL,
[DFVProvision] [decimal] (16, 2) NULL,
[MTMProvision] [decimal] (16, 2) NULL,
[RevisedBusinessSegment] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankingType] [int] NULL,
[RepaymentStartDate] [date] NULL,
[DisbursementDate] [date] NULL,
[RestructureAssetClassAlt_key] [int] NULL,
[RestructureDate] [date] NULL,
[Npa_Qtr] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RestructurePOS] [decimal] (16, 2) NULL,
[RevisedBusSegAlt_Key] [int] NULL,
[Restructure_NPA_Dt] [date] NULL,
[NPA_Provision_per] [decimal] (16, 2) NULL,
[EquityConversionYN] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AdvAcRestructureDetail_Mod_Backup] ADD CONSTRAINT [PK_AdvAcRestructureDetail_new] PRIMARY KEY NONCLUSTERED ([EntityKey]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
