CREATE TABLE [PreMoc].[AdvFacBillDetail]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[AccountEntityId] [int] NOT NULL,
[D2KFacilityID] [int] NULL,
[BillNo] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BillDt] [date] NULL,
[BillAmt] [decimal] (16, 2) NULL,
[BillRefNo] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillPurDt] [date] NULL,
[AdvAmount] [decimal] (16, 2) NULL,
[BillDueDt] [date] NULL,
[BillExtendedDueDt] [date] NULL,
[CrystalisationDt] [date] NULL,
[CommercialisationDt] [date] NULL,
[BillNatureAlt_Key] [smallint] NULL,
[BillAcceptanceDt] [date] NULL,
[UsanceDays] [smallint] NULL,
[DraweeNo] [smallint] NULL,
[DraweeBankName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DrawerName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayeeName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollectingBankName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollectingBranchPlace] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InterestIncome] [decimal] (16, 2) NULL,
[Commission] [decimal] (16, 2) NULL,
[DiscountCharges] [decimal] (16, 2) NULL,
[DelayedInt] [decimal] (16, 2) NULL,
[MarginType] [smallint] NULL,
[MarginAmt] [decimal] (14, 0) NULL,
[CountryAlt_Key] [smallint] NULL,
[BillOsReasonAlt_Key] [smallint] NULL,
[CommodityAlt_Key] [smallint] NULL,
[LcNo] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LcAmt] [decimal] (14, 0) NULL,
[LcIssuingBankAlt_Key] [smallint] NULL,
[LcIssuingBank] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrencyAlt_Key] [smallint] NULL,
[Balance] [decimal] (16, 2) NULL,
[BalanceInCurrency] [decimal] (16, 4) NULL,
[Overdue] [decimal] (14, 0) NULL,
[DerecognisedInterest1] [decimal] (14, 0) NULL,
[DerecognisedInterest2] [decimal] (14, 0) NULL,
[OverDueSinceDt] [date] NULL,
[TotalProv] [decimal] (14, 0) NULL,
[AdditionalProv] [decimal] (14, 0) NULL,
[GenericAddlProv] [decimal] (14, 0) NULL,
[Secured] [decimal] (14, 0) NULL,
[CoverGovGur] [decimal] (16, 2) NULL,
[Unsecured] [decimal] (14, 0) NULL,
[Provsecured] [decimal] (14, 0) NULL,
[ProvUnsecured] [decimal] (14, 0) NULL,
[ProvDicgc] [decimal] (14, 0) NULL,
[npadt] [date] NULL,
[ClaimType] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimCoverAmt] [decimal] (14, 0) NULL,
[ClaimLodgedDt] [date] NULL,
[ClaimLodgedAmt] [decimal] (14, 0) NULL,
[ClaimRecvDt] [date] NULL,
[ClaimReceivedAmt] [decimal] (14, 0) NULL,
[ClaimRate] [decimal] (14, 0) NULL,
[ScrCrError] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefSystemAcid] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdjDt] [date] NULL,
[AdjReasonAlt_Key] [smallint] NULL,
[EntityClosureDate] [date] NULL,
[EntityClosureReasonAlt_Key] [smallint] NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NOT NULL,
[EffectiveToTimeKey] [int] NOT NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[MocStatus] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MocDate] [smalldatetime] NULL,
[MocTypeAlt_Key] [int] NULL,
[ScrCrErrorSeq] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConsigmentExport] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
