CREATE TABLE [PreMoc].[AdvCustOtherDetail]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[CustomerEntityId] [int] NOT NULL,
[OrgCostOfEquip] [decimal] (16, 2) NULL,
[OrgCostOfPlantMech] [decimal] (16, 2) NULL,
[DepValPlant] [decimal] (16, 2) NULL,
[ValLand] [decimal] (16, 2) NULL,
[IECDno] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GroupAlt_Key] [smallint] NULL,
[CustomerSwiftCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SplCatg1Alt_Key] [smallint] NULL,
[SplCatg2Alt_Key] [smallint] NULL,
[SplCatg3Alt_Key] [smallint] NULL,
[SplCatg4Alt_Key] [smallint] NULL,
[CmaEligible] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PFNo] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SupperAnnuationBenefit] [decimal] (16, 2) NULL,
[SupperannuationBenefitValuationDt] [datetime] NULL,
[BusinessCommenceDt] [datetime] NULL,
[CancelObtained] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotConsortiumLimitFunded] [decimal] (16, 2) NULL,
[TotConsortiumLimitNonFunded] [decimal] (16, 2) NULL,
[UpgradationDate] [datetime] NULL,
[CustomerExpiredYN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotWCLimitFunded] [decimal] (16, 2) NULL,
[Flagged_SubSector] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefCustomerId] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NOT NULL,
[EffectiveToTimeKey] [int] NOT NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[MocStatus] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MocDate] [smalldatetime] NULL,
[MocTypeAlt_Key] [int] NULL,
[AnnualExportTurnover] [decimal] (16, 2) NULL,
[FMCNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsEmployee] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsPetitioner] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnderLitigation] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PermiNatureID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BorrUnitFunct] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DtofClosure] [date] NULL,
[NonCoopBorrower] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ArbiAgreement] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransThroughUs] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CutBackArrangement] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankingArrangement] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberBanksNo] [smallint] NULL,
[TotalConsortiumAmt] [decimal] (16, 2) NULL,
[ROC_CFCReportDate] [date] NULL,
[ROC_ChargeFV] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ROC_ChargeFVDt] [date] NULL,
[ROC_ChargeRemark] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ROC_Securities] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ROC_Cover] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ROC_CoveredDt] [datetime] NULL,
[ChargeFiledWith] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FiledDt] [date] NULL,
[EmployeeID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployeeType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Designation] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Placeofposting] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LPersonalConDate] [date] NULL,
[LPersonalConDtls] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecallNoticeDate] [date] NULL,
[RecallNoticeModeID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LegalAuditDate] [date] NULL,
[IrregularityPending] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IrregularityRectiDate] [date] NULL,
[FraudAccoStatus] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreSARFAESINoticeDt] [datetime] NULL,
[FMRNO] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FMRDate] [datetime] NULL,
[GradeScaleAlt_Key] [smallint] NULL,
[FraudNatureRemark] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ROCCoveredCertificateRemark] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReasonsNonCoOperativeBorrower] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StatusNonCoOperativeBorrower] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [PreMoc].[AdvCustOtherDetail] ADD CONSTRAINT [ADVCUSTOTHERDETAIL_CustomerEntityId] PRIMARY KEY NONCLUSTERED ([CustomerEntityId], [EffectiveFromTimeKey], [EffectiveToTimeKey]) ON [PRIMARY]
GO
