CREATE TABLE [PreMoc].[AdvFacBillCal]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[AccountEntityID] [int] NULL,
[FacilityID] [int] NULL,
[Billno] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverDueSinceDt] [date] NULL,
[CAD] [decimal] (18, 2) NULL,
[CADU] [decimal] (18, 2) NULL,
[SystemSecTangAst] [decimal] (18, 2) NULL,
[SystemUnsecured] [decimal] (18, 2) NULL,
[SystemCoverGovGur] [decimal] (18, 2) NULL,
[SystemProvsecured] [decimal] (18, 2) NULL,
[SystemProvUnsecured] [decimal] (18, 2) NULL,
[SystemProvCoverGovGur] [decimal] (18, 2) NULL,
[SystemAdditionalProv] [decimal] (18, 2) NULL,
[SystemTotalProv] [decimal] (18, 2) NULL,
[SystemNPADt] [date] NULL,
[NPASta] [smallint] NULL,
[ComputedClaim] [decimal] (18, 2) NULL,
[AppSFSD] [decimal] (18, 2) NULL,
[AppGovGur] [decimal] (18, 2) NULL,
[AppOthRec] [decimal] (18, 2) NULL,
[AppTotalRV] [decimal] (18, 2) NULL,
[UsedRV] [decimal] (18, 2) NULL,
[NetBalance] [decimal] (18, 2) NULL,
[Deficit] [decimal] (18, 2) NULL,
[BillReferenceTotal] [decimal] (18, 2) NULL,
[BillGovtReferenceTotal] [decimal] (18, 2) NULL,
[RefSystemACID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TimeKey] [int] NULL,
[SetID] [int] NULL,
[Flag] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cadu1] [decimal] (18, 2) NULL,
[Cadu2] [decimal] (18, 2) NULL,
[Cadu3] [decimal] (18, 2) NULL,
[AppPriRV] [decimal] (18, 2) NULL,
[AppCollRV] [decimal] (18, 2) NULL
) ON [PRIMARY]
GO
