CREATE TABLE [PreMoc].[AdvFacDlCal]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[AccountEntityID] [int] NULL,
[OverDueSinceDt] [date] NULL,
[CAD] [decimal] (18, 2) NULL,
[CADU] [decimal] (18, 2) NULL,
[SystemNPADt] [date] NULL,
[NPASta] [smallint] NULL,
[Principal] [decimal] (18, 2) NULL,
[CADRefBalance] [decimal] (18, 2) NULL,
[CADURefBalance] [decimal] (18, 2) NULL,
[RecoveryforCAD] [decimal] (18, 2) NULL,
[RecoveryforCADU] [decimal] (18, 2) NULL,
[RecoveryforOverdue] [decimal] (18, 2) NULL,
[OverdueRefIdealBalance] [decimal] (18, 2) NULL,
[CADRefIdealBalance] [decimal] (18, 2) NULL,
[CADURefidealbalance] [decimal] (18, 2) NULL,
[NetCADAmountInDefault] [decimal] (18, 2) NULL,
[NetCADUAmountInDefault] [decimal] (18, 2) NULL,
[AppSFSD] [decimal] (18, 2) NULL,
[AppGovGur] [decimal] (18, 2) NULL,
[AppTotalRV] [decimal] (18, 2) NULL,
[UsedRV] [decimal] (18, 2) NULL,
[NetBalance] [decimal] (18, 2) NULL,
[Deficit] [decimal] (18, 2) NULL,
[ComputedClaim] [decimal] (18, 2) NULL,
[AgriDueDt] [date] NULL,
[RefSystemACID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TimeKey] [int] NULL,
[SetID] [int] NULL,
[Flag] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cadu1] [decimal] (18, 2) NULL,
[Cadu2] [decimal] (18, 2) NULL,
[Cadu3] [decimal] (18, 2) NULL,
[AppPriRV] [decimal] (18, 2) NULL,
[AppCollRV] [decimal] (18, 2) NULL
) ON [PRIMARY]
GO
