CREATE TABLE [PreMoc].[InvestmentFinancialDetail]
(
[EntityKey] [bigint] NOT NULL,
[InvEntityId] [int] NOT NULL,
[RefInvID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HoldingNature] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrencyAlt_Key] [tinyint] NULL,
[CurrencyConvRate] [decimal] (12, 4) NULL,
[BookType] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BookValue] [decimal] (18, 2) NULL,
[BookValueINR] [decimal] (18, 2) NULL,
[MTMValue] [decimal] (18, 2) NULL,
[MTMValueINR] [decimal] (18, 2) NULL,
[EncumberedMTM] [decimal] (18, 2) NULL,
[AssetClass_AltKey] [tinyint] NULL,
[NPIDt] [date] NULL,
[TotalProvison] [decimal] (18, 2) NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NOT NULL,
[EffectiveToTimeKey] [int] NOT NULL,
[CreatedBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[DBTDate] [date] NULL,
[LatestBSDate] [date] NULL,
[Interest_DividendDueDate] [date] NULL,
[Interest_DividendDueAmount] [decimal] (16, 2) NULL,
[PartialRedumptionDueDate] [date] NULL,
[PartialRedumptionSettledY_N] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FLGDEG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEGREASON] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DPD] [int] NULL,
[FLGUPG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpgDate] [date] NULL,
[PROVISIONALT_KEY] [int] NULL,
[InitialAssetAlt_Key] [int] NULL,
[InitialNPIDt] [date] NULL,
[RefIssuerID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DPD_Maturity] [smallint] NULL,
[DPD_DivOverdue] [int] NULL,
[FinalAssetClassAlt_Key] [int] NULL,
[PartialRedumptionDPD] [smallint] NULL,
[Asset_Norm] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISIN] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetClass] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GL_Code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GL_Description] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OVERDUE_AMOUNT] [decimal] (10, 2) NULL,
[FlgSMA] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMA_Dt] [date] NULL,
[SMA_Class] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMA_Reason] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddlProvision] [decimal] (18, 2) NULL,
[AddlProvisionPer] [decimal] (5, 2) NULL,
[MocBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOC_Date] [date] NULL,
[FlgMoc] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOC_Reason] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
