CREATE TABLE [PreMoc].[CUSTOMERBASICDETAIL]
(
[CustomerEntityId] [int] NOT NULL,
[CustomerId] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[D2kCustomerid] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ParentBranchCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerName] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CustomerInitial] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSinceDt] [date] NULL,
[ConstitutionAlt_Key] [smallint] NULL,
[OccupationAlt_Key] [smallint] NULL,
[ReligionAlt_Key] [smallint] NULL,
[CasteAlt_Key] [smallint] NULL,
[FarmerCatAlt_Key] [smallint] NULL,
[GaurdianSalutationAlt_Key] [smallint] NULL,
[GaurdianName] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GuardianType] [smallint] NULL,
[CustSalutationAlt_Key] [smallint] NULL,
[MaritalStatusAlt_Key] [smallint] NULL,
[AssetClass] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BIITransactionCode] [bit] NULL,
[D2K_REF_NO] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ScrCrError] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferenceAcNo] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustCRM_RatingAlt_Key] [smallint] NULL,
[CustCRM_RatingDt] [date] NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NOT NULL,
[EffectiveToTimeKey] [int] NOT NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[FLAG] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MocStatus] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MocDate] [smalldatetime] NULL,
[MocTypeAlt_Key] [smallint] NULL,
[CommonMocTypeAlt_Key] [smallint] NULL,
[LandHolding] [decimal] (16, 2) NULL,
[ScrCrErrorSeq] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Remark] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTOMER_KEY] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
