CREATE TABLE [PreMoc].[AdvExternalRatingDetail]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[CustomerEntityId] [int] NULL,
[AccountEntityId] [int] NULL,
[RelationEntityID] [int] NULL,
[RatingAgencyAlt_Key] [smallint] NULL,
[RatingAlt_Key] [smallint] NULL,
[RatingDt] [date] NULL,
[RatingRenewalDt] [date] NULL,
[RatingExpireDt] [date] NULL,
[RefCustomerId] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefSystemAcId] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorisationStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[CreatedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL,
[ModifiedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateModified] [smalldatetime] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateApproved] [smalldatetime] NULL,
[D2Ktimestamp] [timestamp] NOT NULL,
[MocStatus] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MocDate] [smalldatetime] NULL,
[MocTypeAlt_Key] [int] NULL,
[AgencyChangeAlt_Key] [smallint] NULL,
[ChangeAuthorityAlt_Key] [smallint] NULL,
[ReferenceNo] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderDt] [date] NULL,
[RatingAmt] [decimal] (35, 2) NULL,
[RatingAction] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
