CREATE TABLE [PreMoc].[AdvFacCCCal]
(
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[AccountEntityID] [int] NULL,
[OverDueSinceDt] [date] NULL,
[CAD] [decimal] (18, 0) NULL,
[CADU] [decimal] (18, 0) NULL,
[OverDue] [decimal] (18, 0) NULL,
[SystemNPADt] [date] NULL,
[NPASta] [smallint] NULL,
[AppSFSD] [decimal] (18, 0) NULL,
[AppGovGur] [decimal] (18, 0) NULL,
[AppTotalRV] [decimal] (18, 0) NULL,
[UsedRV] [decimal] (18, 0) NULL,
[PreQtrConExcs] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurQtrConExcs] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FinCumCredit] [decimal] (18, 0) NULL,
[KCCduedt] [date] NULL,
[RecComponentUsed] [decimal] (18, 0) NULL,
[PreQtrCredit] [decimal] (18, 0) NULL,
[PreQtrInt] [decimal] (18, 0) NULL,
[CurQtrCredit] [decimal] (18, 0) NULL,
[CurQtrInt] [decimal] (18, 0) NULL,
[PreQtrBal] [decimal] (18, 0) NULL,
[DtReviewDeg] [date] NULL,
[DtStockDeg] [date] NULL,
[DtConExcessDeg] [date] NULL,
[DtCADDeg] [date] NULL,
[NetBalance] [decimal] (18, 0) NULL,
[Deficit] [decimal] (18, 2) NULL,
[ComputedClaim] [decimal] (18, 2) NULL,
[RefSystemACID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TimeKey] [int] NULL,
[SetID] [int] NULL,
[Flag] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DtLastCrDeg] [date] NULL,
[ODDtDeg] [date] NULL,
[Cadu1] [decimal] (18, 2) NULL,
[Cadu2] [decimal] (18, 2) NULL,
[Cadu3] [decimal] (18, 2) NULL,
[AppPriRV] [decimal] (18, 2) NULL,
[AppCollRV] [decimal] (18, 2) NULL
) ON [PRIMARY]
GO
