CREATE TABLE [PRO].[PUI_CAL]
(
[CustomerEntityID] [int] NULL,
[AccountEntityId] [int] NULL,
[ProjectCategoryAlt_Key] [int] NULL,
[ProjectSubCategoryAlt_key] [int] NULL,
[DelayReasonChangeinOwnership] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProjectAuthorityAlt_key] [int] NULL,
[OriginalDCCO] [date] NULL,
[OriginalProjectCost] [decimal] (16, 2) NULL,
[OriginalDebt] [decimal] (16, 2) NULL,
[Debt_EquityRatio] [decimal] (16, 2) NULL,
[ChangeinProjectScope] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FreshOriginalDCCO] [date] NULL,
[RevisedDCCO] [date] NULL,
[CourtCaseArbitration] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIOReferenceDate] [date] NULL,
[CIODCCO] [date] NULL,
[TakeOutFinance] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetClassSellerBookAlt_key] [int] NULL,
[NPADateSellerBook] [date] NULL,
[Restructuring] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InitialExtension] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BeyonControlofPromoters] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DelayReasonOther] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FLG_UPG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FLG_DEG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEFAULT_REASON] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProjCategory] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NPA_DATE] [date] NULL,
[PUI_ProvPer] [decimal] (5, 2) NULL,
[RestructureDate] [date] NULL,
[ActualDCCO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActualDCCO_Date] [date] NULL,
[UpgradeDate] [date] NULL,
[FinalAssetClassAlt_Key] [int] NULL,
[DPD_Max] [int] NULL,
[EffectiveFromTimeKey] [int] NULL,
[EffectiveToTimeKey] [int] NULL,
[EntityKey] [int] NOT NULL IDENTITY(1, 1),
[SecuredProvision] [decimal] (22, 2) NULL,
[UnSecuredProvision] [decimal] (22, 2) NULL,
[RevisedDebt] [decimal] (16, 2) NULL,
[CostOverrun] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RevisedProjectCost] [decimal] (16, 2) NULL,
[CostOverRunPer] [decimal] (5, 2) NULL,
[FinnalDCCO_Date] [date] NULL,
[IsChanged] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProjectOwnerShipAlt_Key] [smallint] NULL
) ON [PRIMARY]
GO
